import type { ApplicationData } from '../types'

export const basements: ApplicationData = {
  id: 'basements',
  categoryId: 'civil',
  pt: {
    meta: {
      title: 'Impermeabilização de Caves com EPDM | Membriko',
      description: 'Impermeabilização de caves e estruturas subterrâneas com membrana EPDM. Sistemas pré-aplicado, pós-aplicado e tanking interior. Resistência a pressão hidrostática e radão. Portugal.',
      keywords: ['impermeabilização cave EPDM', 'cave húmida solução', 'membrana cave betão', 'impermeabilização piso enterrado', 'EPDM cave Portugal'],
    },
    hero: {
      headline: 'Caves Secas e Protegidas com Membrana EPDM',
      subtitle: 'Converta a sua cave húmida numa cave funcional e seca com o sistema de impermeabilização EPDM — a solução definitiva para pisos enterrados, resistente à pressão hidrostática e ao radão.',
      stats: [
        { value: '50+', label: 'Anos de proteção garantida' },
        { value: '200 kPa', label: 'Estanquidade hidrostática (EN 1928)' },
        { value: '400%', label: 'Elongação sem rutura' },
        { value: '20 anos', label: 'Garantia' },
      ],
    },
    problem: {
      title: 'O Desafio das Caves Húmidas',
      description: 'Caves húmidas são um problema comum em Portugal, especialmente em edifícios construídos antes de 2000 com impermeabilização deficiente. A falha manifesta-se silenciosamente — humidade que corrói armaduras, deteriora instalações e alimenta bolores — e quando a reparação se torna urgente, o custo é 5-15 vezes o de uma impermeabilização correta na origem.',
      points: [
        'Infiltrações silenciosas corroem armaduras de betão durante anos antes da manifestação visível — dano estrutural progressivo',
        'Humidade persistente em caves cria bolores e fungos nocivos à saúde — segunda causa de cancro do pulmão em zonas de radão',
        'Reparações temporárias (tintas impermeáveis, injeções) falham em 2-5 anos e criam ciclos de despesa sem solução definitiva',
        'Cave húmida ou inutilizável representa desvalorização de €20.000-€50.000+ no imóvel',
      ],
    },
    solution: {
      title: 'A Solução EPDM para Caves',
      description: 'A membrana EPDM cria um envelope impermeável contínuo (tanking) em torno de toda a estrutura subterrânea. Aprovada a 200 kPa (20 m de coluna de água) pela EN 1928, oferece fator de segurança de 5-20 vezes para caves standard a 3-5 m de profundidade.',
      points: [
        'Sistema de tanking EPDM com continuidade total — sem emendas na junção laje/parede (o ponto de maior risco)',
        'Aprovado a 200 kPa EN 1928 Método A — fator de segurança de 5-20× para caves portuguesas típicas',
        'Proteção simultânea contra água e radão — reconhecido pela DGS como barreira eficaz (BRE 211, EN 13829)',
        'Sistema pré-aplicado para obras novas ou tanking interior para reabilitação sem escavação exterior',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Solução Definitiva (50+ Anos)', description: 'Ao contrário de tintas (2-5 anos) e injeções (5-15 anos) que falham progressivamente, o EPDM aprovado a 200 kPa (EN 1928) é uma solução estrutural com 50+ anos de vida útil documentada. Uma decisão de engenharia tomada uma vez, corretamente.' },
      { icon: 'Droplets', title: 'Proteção contra Radão', description: 'O EPDM é reconhecido pela DGS e pela BRE (Grã-Bretanha) como barreira de retenção de radão eficaz. Em zonas de risco em Portugal (Beira Interior, Trás-os-Montes, Serra da Estrela), a membrana reduz a entrada de Rn-222 a níveis abaixo do nível de ação de 300 Bq/m³ (Portaria 353-A/2013).' },
      { icon: 'Home', title: 'Cave Reutilizável para Habitação', description: 'Uma cave completamente estanque pode ser transformada em espaço habitável, garagem, escritório ou zona técnica. O retorno sobre o investimento — €20.000-€50.000+ de valorização do imóvel — excede amplamente o custo da obra de impermeabilização.' },
      { icon: 'Euro', title: 'Custo de Reparação Estrutural Evitado', description: 'O custo de reparação estrutural de cave com armaduras corroídas é 5-15 vezes o custo da impermeabilização original. A equação económica a favor da qualidade é irrefutável: investir corretamente na impermeabilização é sempre mais barato do que reparar o dano estrutural.' },
      { icon: 'Leaf', title: 'Saúde e Qualidade do Ar Interior', description: 'Eliminação de humidade e bolores melhora a qualidade do ar interior de todo o edifício. Em zonas de risco geológico de radão (Portugal Centro e Norte), a membrana EPDM é o sistema de mitigação recomendado — o radão é a segunda causa de cancro do pulmão na Europa (IARC/OMS).' },
      { icon: 'Wrench', title: 'Sem Escavação Exterior para Reabilitação', description: 'O sistema de tanking interior (EPDM ancorado mecanicamente) é instalado sem escavar à volta do edifício — obra completamente interior. O sistema exterior (pós-aplicado) é instalado durante a construção ou quando há acesso à face exterior.' },
    ],
    specs: [
      { label: 'Espessura', value: '1,5 mm (caves standard) / 2,0 mm (pressão alta ou crítico)' },
      { label: 'Estanquidade hidrostática', value: 'Aprovado a 200 kPa (EN 1928 Método A — 20 m coluna de água)' },
      { label: 'Elongação na rutura', value: '≥ 400% (acomoda abertura de fenda sísmica de 50+ mm)' },
      { label: 'Resistência a sulfatos do solo', value: 'Classes EA1-EA4 (EN 206) — excelente' },
      { label: 'Retenção de radão', value: 'Conforme BRE 211 / EN 13829 / DGS Portugal' },
      { label: 'pH suportado', value: '4 a 12 — resistente ao ambiente alcalino do betão' },
      { label: 'Temperatura de serviço', value: '-50°C a +130°C' },
      { label: 'Norma de produto', value: 'EN 13967 (marcação CE para aplicações subterrâneas)' },
    ],
    installationSteps: [
      { step: 1, title: 'Diagnóstico Completo', description: 'Avaliação da dimensão e localização das infiltrações. Identificação das causas (lençol freático, escorrência superficial, condensação). Medição de humidade nas paredes e laje. Em zonas de risco de radão, medição de concentração de Rn-222 (Portaria 353-A/2013).' },
      { step: 2, title: 'Tratamento de Infiltrações Ativas', description: 'Paragem de fluxo ativo com argamassa hidráulica de presa rápida — pré-requisito antes da instalação da membrana. Injeção de poliuretano em fissuras com fluxo ativo. Sem fluxo ativo, a membrana não pode ser instalada.' },
      { step: 3, title: 'Preparação das Superfícies', description: 'Remoção de revestimentos instáveis, eflorescências e salitres. Regularização de superfícies irregulares. Arredondamento de cantos a 45° e preenchimento de ressaltos. Resistência ao arranque mínima de 0,5 N/mm².' },
      { step: 4, title: 'Sistema de Drenagem Sub-Laje (Radão)', description: 'Nas zonas de risco de radão, instalação de geocompósito drenante sob a laje com risers de ventilação passiva ligados ao exterior ou cobertura. A despressurização sub-laje impede a entrada de Rn-222 mesmo em caso de dano localizado da membrana.' },
      { step: 5, title: 'Instalação da Membrana EPDM', description: 'Sistema pré-aplicado (obras novas): EPDM fixado à contenção antes do betão. Sistema pós-aplicado (exterior acessível): EPDM colado à face exterior do betão. Sistema de tanking interior (reabilitação): EPDM ancorado mecanicamente ao interior das paredes e laje, com peças de transição contínua laje/parede sem emenda no canto.' },
      { step: 6, title: 'Pontos Singulares e Continuidade Total', description: 'Junção laje/parede com continuidade total — membrana dobra de horizontal para vertical sem emenda no ângulo de maior risco. Penetrações de tubagens e cabos com mangas EPDM prefabricadas. Nenhum mástique ou silicone como vedante principal.' },
      { step: 7, title: 'Revestimentos Interiores e Garantia', description: 'Aplicação de revestimentos interiores sobre o EPDM (gesso, isolamento, pladur) para acabamento de qualidade. Entrega de dossier com planta as-built, documentação fotográfica, resultados de ensaios e garantia de 20 anos.' },
    ],
    techniques: [
      {
        title: 'Sistema Pré-Aplicado / Blind-Side (Obras Novas)',
        description: 'Para obras novas com face exterior inacessível após construção (paredes de estacas, berlin, construção top-down), EPDM fixado à contenção antes do betão. O betão estrutural liga diretamente à face interna da membrana através de geotêxtil de ligação — sem percurso de migração longitudinal.',
        pros: ['Elimina completamente o percurso de migração de água entre membrana e betão', 'Aplicável quando a face exterior não é acessível após construção', 'Sistema positivo — água bloqueada antes de contactar o betão estrutural', 'Ideal para Lisboa (aluviões) e Porto (granito fraturado com drenagem concentrada)'],
        cons: ['Apenas aplicável durante a fase de construção, não em reabilitação', 'Requer coordenação rigorosa com faseamento de cofragem e betonagem'],
      },
      {
        title: 'Sistema Pós-Aplicado Exterior (Exterior Acessível)',
        description: 'Para caves em que a face exterior é acessível durante a construção ou com escavação possível, EPDM colado totalmente à face exterior do betão antes do aterro. Sistema positivo de máxima eficácia — a água é bloqueada antes de contactar o betão.',
        pros: ['Máxima eficácia — sistema positivo, nenhuma água contacta o betão', 'Sem perda de espaço interior', 'Sistema mais durável para pressões hidrostáticas elevadas (>5 m coluna de água)', 'Compatível com geocompósito drenante exterior para alívio de pressão'],
        cons: ['Requer acesso exterior — escavação periférica', 'Não aplicável em caves entre miteiras ou com edifícios adjacentes'],
      },
      {
        title: 'Tanking Interior (Reabilitação Sem Escavação)',
        description: 'Para reabilitação de caves existentes com infiltrações sem acesso à face exterior, EPDM ancorado mecanicamente ao interior das paredes e laje. Cria câmara de ar que drena eventuais infiltrações para canal perimetral. Solução de obra totalmente interior.',
        pros: ['Obra totalmente interior — sem escavação, mínima perturbação', 'Aplicável a caves em banda ou com edifícios adjacentes', 'Canal de drenagem perimetral como sistema de segurança complementar', 'Compatível com radão — instalação de risers de ventilação integrada'],
        cons: ['Sistema negativo — não impede a água de contactar o betão; gere a entrada', 'Ligeira redução do espaço interior pela câmara de ar (30-50 mm por parede)'],
      },
    ],
    comparison: [
      { feature: 'Durabilidade e vida útil', epdm: '50+ anos sem re-intervenção', alternatives: [{ name: 'Tinta impermeável interior', value: '2-5 anos — falha por pressão hidrostática' }, { name: 'Injeção de resina epóxi', value: '5-15 anos — colmata fissuras existentes' }] },
      { feature: 'Eficácia a pressão hidrostática', epdm: 'Aprovado a 200 kPa (EN 1928)', alternatives: [{ name: 'Tinta impermeável interior', value: 'Nenhuma — levanta com pressão hidrostática' }, { name: 'Sistema dreno + bomba sump', value: 'Gere entrada de água (não para)' }] },
      { feature: 'Proteção contra radão', epdm: 'Eficaz — BRE 211 / EN 13829 / DGS', alternatives: [{ name: 'Tinta impermeável interior', value: 'Nenhuma eficácia para radão' }, { name: 'Sistema cristalino cimentício', value: 'Eficácia limitada — não é barreira de gás' }] },
      { feature: 'Capacidade de acomodar movimentos sísmicos', epdm: '400% elongação — fissuração sísmica até 50+ mm', alternatives: [{ name: 'Sistema cristalino cimentício', value: 'Zero — falha frágil em fissuras sísmicas' }, { name: 'Bentonite GCL', value: 'Limitada — risco de dessecação sazonal' }] },
      { feature: 'Resistência a sulfatos do solo', epdm: 'Excelente — Classes EA1-EA4 EN 206', alternatives: [{ name: 'Betume modificado', value: 'Moderada — risco de saponificação' }, { name: 'Bentonite GCL', value: 'Risco de troca de iões de cálcio em solos calcários' }] },
      { feature: 'Custo de ciclo de vida (50 anos)', epdm: 'Mais baixo — sem substituições', alternatives: [{ name: 'Tinta impermeável interior', value: '5-8 re-aplicações em 50 anos' }, { name: 'Sistema dreno + bomba sump', value: 'Consumo elétrico + substituição de bomba' }] },
    ],
    climate: [
      { zone: 'Lisboa e Vale do Tejo (Aluviões e Lençol Elevado)', description: 'Caves na Baixa de Lisboa, Chiado, Almada ribeirinha e Setúbal têm lençol freático a 1-3 m de profundidade em terreno aluvionar. O sistema EPDM aprovado a 200 kPa (20 m de coluna de água) cobre com fator de segurança de 5-10× a pressão típica de 20-30 kPa nestas localizações.' },
      { zone: 'Beira Interior e Trás-os-Montes (Radão)', description: 'As zonas de granito uranífero do interior de Portugal têm as maiores concentrações de radão na Europa continental. O EPDM reconhecido pela DGS como barreira de radão (BRE 211, EN 13829) é obrigatório em caves nestas regiões — combinado com despressurização sub-laje passiva.' },
      { zone: 'Porto e Norte (Granito Fraturado)', description: 'O granito alterado do Porto e norte tem nível freático moderado mas com fraturas que conduzem água de forma concentrada. O EPDM acomoda aumentos súbitos de caudal em frentes de fratura sem que a pressão localizada comprometa a membrana — ao contrário de sistemas rígidos.' },
      { zone: 'Zonas Costeiras (Cloretos e Intrusão Salina)', description: 'Caves em zonas costeiras (Algarve, Alentejo Litoral, Estuários) têm risco adicional de intrusão salina e cloretos. O EPDM é completamente inerte a água salgada e soluções de cloreto — protegendo o betão do ataque em ambiente de maré ou lençol freático salobro.' },
      { zone: 'Alentejo e Interior Sul (Argilas Expansivas)', description: 'Caves fundadas em solos argilosos expansivos do Alentejo têm risco de assentamentos diferenciais sazonais (argilas que expandem no inverno húmido e contraem no verão seco). A elongação de 400% do EPDM acomoda estes movimentos sem rutura — sistemas cimentícios fissurariam.' },
    ],
    faqs: [
      { question: 'A solução EPDM interior funciona com pressão hidrostática elevada?', answer: 'Sim. O sistema de ancoragem mecânica do tanking interior é dimensionado para resistir à pressão hidrostática específica de cada caso. O EPDM é aprovado a 200 kPa (20 m de coluna de água) pela EN 1928 Método A — para uma cave standard a 3-5 m de profundidade, o fator de segurança é de 5-20 vezes.' },
      { question: 'Qual é a diferença entre o sistema pré-aplicado e o tanking interior?', answer: 'O sistema pré-aplicado (blind-side) é instalado sobre a contenção antes do betão, em obras novas — o betão liga diretamente à membrana. O tanking interior é instalado no interior da cave existente, sem escavar — cria câmara de ar entre EPDM e parede que drena para canal perimetral. O sistema pré-aplicado é mais eficaz; o tanking interior é a solução quando não há acesso exterior.' },
      { question: 'O EPDM protege contra o radão em zonas de risco geológico?', answer: 'Sim. O EPDM é reconhecido pela DGS e pela BRE (BRE 211) como barreira de retenção de radão eficaz para nova construção e reabilitação. Para localizações de maior risco (Beira Interior, Trás-os-Montes), a Membriko especifica a membrana EPDM combinada com sistema de despressurização sub-laje passivo (geocompósito + risers de ventilação), conforme as orientações da DGS e a Portaria 353-A/2013.' },
      { question: 'Como se trata o ponto crítico da junção laje/parede?', answer: 'A junção laje/parede é o ponto de maior risco em qualquer impermeabilização de cave. A Membriko resolve com continuidade total: a membrana EPDM da laje dobra na vertical sobre a parede com largura mínima de 300 mm, sem emenda no ângulo de transição. Peças de enchimento EPDM pré-formadas (fillets) são coladas no ângulo interior para eliminar tensões de tração. Uma única membrana sem emenda transversal no ponto de maior risco.' },
      { question: 'Quanto tempo demora a obra de impermeabilização de uma cave?', answer: 'Uma cave de 50-100 m² leva tipicamente 5-10 dias de obra interior, incluindo preparação, paragem de infiltrações ativas e instalação da membrana. Sem escavação exterior, a perturbação é mínima. Em obras novas com sistema pré-aplicado, a coordenação com o empreiteiro geral é feita antes do início das betonagens.' },
      { question: 'O EPDM resiste aos sulfatos e químicos agressivos do solo?', answer: 'Sim. O EPDM tem excelente resistência a sulfatos (Classes de Exposição EA1-EA4 conforme EN 206), cloretos, ácidos orgânicos e hidrocarbonetos de petróleo. Para locais com contaminação identificada (aterros antigos, postos de combustível, zonas industriais), a Membriko realiza avaliação de compatibilidade química com base no relatório de caracterização do terreno.' },
      { question: 'Como se repara o EPDM se for danificado por uma obra posterior na cave?', answer: 'Reparação por patch de EPDM da mesma espessura e formulação, colado com primer QuickPrime e fita QuickSeam de 150 mm sobre a zona danificada, com sobreposição mínima de 75 mm em todas as direções sobre a zona limpa e seca. Para danos em zonas sob betão ou aterro, a Membriko realiza diagnóstico com deteção elétrica de fugas (ELD) antes de definir a estratégia de reparação.' },
      { question: 'O EPDM acomoda os movimentos sísmicos em caves em Lisboa e no Algarve?', answer: 'Sim. A elongação de 400% do EPDM acomoda movimentos de 50+ mm e aberturas de fenda sísmica de vários milímetros — com fator de segurança muito superior a qualquer sistema rígido. Para estruturas subterrâneas em Lisboa (Zona Sísmica 1.3) e Algarve, a Membriko pode confirmar documentalmente que a capacidade de deformação da membrana é compatível com os valores de deriva calculados pelo estrutural conforme Eurocódigo 8.' },
      { question: 'Qual a garantia da Membriko para impermeabilização de caves?', answer: 'A Membriko emite garantia de instalação de 20 anos para todos os trabalhos de impermeabilização de caves e estruturas subterrâneas. Esta garantia é complementar à garantia do fabricante da membrana e ao período de responsabilidade por defeitos de 10 anos (Código Civil, art.º 1225º). O certificado de garantia, o relatório de inspeção fotográfico e a planta as-built são entregues ao cliente no final da obra.' },
    ],
    relatedSlugs: ['foundations', 'underground-parking', 'retaining-walls'],
  },
  en: {
    meta: {
      title: 'Basement Waterproofing with EPDM Membrane | Membriko',
      description: 'Basement and underground structure waterproofing with EPDM membrane. Pre-applied, post-applied and internal tanking systems. Hydrostatic pressure and radon resistance. Portugal.',
      keywords: ['basement waterproofing EPDM', 'damp basement solution', 'basement membrane concrete', 'buried floor waterproofing', 'EPDM basement Portugal'],
    },
    hero: {
      headline: 'Dry, Protected Basements with EPDM Membrane',
      subtitle: 'Convert your damp basement into a functional, dry space with the EPDM waterproofing system — the definitive solution for below-ground floors, resistant to hydrostatic pressure and radon.',
      stats: [
        { value: '50+', label: 'Years of guaranteed protection' },
        { value: '200 kPa', label: 'Hydrostatic resistance (EN 1928)' },
        { value: '400%', label: 'Elongation without failure' },
        { value: '20 years', label: 'Guarantee' },
      ],
    },
    problem: {
      title: 'The Damp Basement Challenge',
      description: 'Damp basements are common in Portugal, especially in buildings constructed before 2000 with deficient waterproofing. Failure manifests silently — moisture corroding reinforcement, deteriorating installations and feeding mould — and when repair becomes urgent, the cost is 5-15 times the original waterproofing.',
      points: [
        'Silent infiltrations corrode concrete reinforcement for years before visible manifestation — progressive structural damage',
        'Persistent basement moisture creates health-harmful mould — radon gas in at-risk geological zones is the second cause of lung cancer',
        'Temporary repairs (waterproof paints, injections) fail in 2-5 years creating expense cycles without definitive solution',
        'Wet or unusable basement represents property devaluation of €20,000-€50,000+ depending on size',
      ],
    },
    solution: {
      title: 'The EPDM Solution for Basements',
      description: 'EPDM membrane creates a continuous impermeable envelope (tanking) around the entire underground structure. Approved at 200 kPa (20 m water column) per EN 1928, it offers a safety factor of 5-20 times for standard basements at 3-5 m depth.',
      points: [
        'EPDM tanking system with full continuity — no seam at the slab/wall junction (the highest-risk point)',
        'Approved at 200 kPa EN 1928 Method A — 5-20× safety factor for typical Portuguese basements',
        'Simultaneous water and radon protection — recognised by Portugal\'s DGS as effective barrier (BRE 211, EN 13829)',
        'Pre-applied system for new construction or internal tanking for rehabilitation without exterior excavation',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Definitive Solution (50+ Years)', description: 'Unlike paints (2-5 years) and injections (5-15 years) that progressively fail, EPDM approved at 200 kPa (EN 1928) is a structural solution with documented 50+ year service life. An engineering decision made once, correctly.' },
      { icon: 'Droplets', title: 'Radon Gas Protection', description: 'EPDM is recognised by Portugal\'s DGS and the UK BRE as an effective radon retention barrier. In at-risk zones in Portugal (Beira Interior, Trás-os-Montes, Serra da Estrela), the membrane reduces Rn-222 entry to levels below the 300 Bq/m³ action level (Portaria 353-A/2013).' },
      { icon: 'Home', title: 'Reusable Basement for Habitation', description: 'A completely watertight basement can be transformed into habitable space, garage, office or technical area. Return on investment — €20,000-€50,000+ property value increase — far exceeds the waterproofing cost.' },
      { icon: 'Euro', title: 'Structural Repair Costs Avoided', description: 'The cost of structural repair for a basement with corroded reinforcement is 5-15 times the original waterproofing cost. The economic case for quality waterproofing is irrefutable: investing correctly in waterproofing is always cheaper than repairing structural damage.' },
      { icon: 'Leaf', title: 'Health and Indoor Air Quality', description: 'Elimination of moisture and mould significantly improves indoor air quality throughout the building. In geological radon risk zones (Central and Northern Portugal), EPDM membrane is the recommended mitigation system — radon is the second cause of lung cancer in Europe (IARC/WHO).' },
      { icon: 'Wrench', title: 'No Exterior Excavation for Rehabilitation', description: 'The internal tanking system (mechanically anchored EPDM) is installed without excavating around the building — fully interior work. The external system (post-applied) is installed during construction or when exterior face access is available.' },
    ],
    specs: [
      { label: 'Thickness', value: '1.5 mm (standard basements) / 2.0 mm (high pressure or critical)' },
      { label: 'Hydrostatic watertightness', value: 'Approved at 200 kPa (EN 1928 Method A — 20 m water column)' },
      { label: 'Elongation at break', value: '≥ 400% (accommodates seismic crack opening of 50+ mm)' },
      { label: 'Soil sulphate resistance', value: 'Classes EA1-EA4 (EN 206) — excellent' },
      { label: 'Radon retention', value: 'Per BRE 211 / EN 13829 / DGS Portugal' },
      { label: 'pH range', value: '4 to 12 — resistant to concrete alkaline environment' },
      { label: 'Service temperature', value: '-50°C to +130°C' },
      { label: 'Product standard', value: 'EN 13967 (CE marking for underground applications)' },
    ],
    installationSteps: [
      { step: 1, title: 'Full Diagnosis', description: 'Assessment of infiltration extent and location. Cause identification (water table, surface runoff, condensation). Moisture measurement in walls and slab. In radon risk zones, Rn-222 concentration measurement (Portaria 353-A/2013).' },
      { step: 2, title: 'Active Infiltration Treatment', description: 'Stopping active water flow with rapid-set hydraulic mortar — prerequisite before membrane installation. Polyurethane injection into cracks with active flow. Without stopping active flow, membrane installation is not possible.' },
      { step: 3, title: 'Surface Preparation', description: 'Removal of unstable coatings, efflorescence and salts. Levelling of irregular surfaces. 45° chamfering of corners and filling of protrusions. Minimum pull-off resistance of 0.5 N/mm².' },
      { step: 4, title: 'Sub-Slab Drainage System (Radon)', description: 'In radon risk zones, installation of drainage geocomposite under the slab with passive ventilation risers connected to exterior or roof. Sub-slab depressurisation prevents Rn-222 entry even in case of localised membrane damage.' },
      { step: 5, title: 'EPDM Membrane Installation', description: 'Pre-applied system (new construction): EPDM fixed to excavation support before concrete. Post-applied system (accessible exterior): EPDM fully bonded to exterior concrete face. Internal tanking (rehabilitation): EPDM mechanically anchored to interior of walls and slab, with continuous slab/wall transition pieces without seam at the critical corner.' },
      { step: 6, title: 'Singular Points and Full Continuity', description: 'Slab/wall junction with full continuity — membrane folds from horizontal to vertical without seam at the highest-risk angle. Pipe and cable penetrations with pre-fabricated EPDM sleeves. No mastic or silicone as primary sealant at any point.' },
      { step: 7, title: 'Interior Finishes and Warranty', description: 'Application of interior finishes over EPDM (plaster, insulation, plasterboard) for quality finish. Delivery of dossier with as-built plan, photographic documentation, test results and 20-year warranty.' },
    ],
    techniques: [
      {
        title: 'Pre-Applied / Blind-Side System (New Construction)',
        description: 'For new construction with inaccessible exterior face after construction (bored pile walls, sheet piles, top-down construction), EPDM fixed to excavation support before concrete. Structural concrete bonds directly to membrane inner face through bonding geotextile — no longitudinal migration pathway.',
        pros: ['Completely eliminates sub-membrane water migration pathway between membrane and concrete', 'Applicable when exterior face is not accessible after construction', 'Positive system — water blocked before contacting structural concrete', 'Ideal for Lisbon (alluvial ground) and Porto (fractured granite with concentrated drainage)'],
        cons: ['Only applicable during construction phase, not in rehabilitation', 'Requires rigorous coordination with formwork and concreting phasing'],
      },
      {
        title: 'Post-Applied External System (Accessible Exterior)',
        description: 'For basements where the exterior face is accessible during construction or with feasible excavation, EPDM fully bonded to the exterior concrete face before backfilling. Maximum-effectiveness positive system — water blocked before contacting concrete.',
        pros: ['Maximum effectiveness — positive system, no water contacts concrete', 'No interior space loss', 'Most durable system for high hydrostatic pressures (>5 m water column)', 'Compatible with exterior drainage geocomposite for pressure relief'],
        cons: ['Requires exterior access — perimeter excavation', 'Not applicable in terraced basements or with adjacent buildings'],
      },
      {
        title: 'Internal Tanking (Rehabilitation Without Excavation)',
        description: 'For rehabilitation of existing basements with infiltrations without exterior face access, EPDM mechanically anchored to the interior of walls and slab. Creates air cavity draining any infiltrations to perimeter channel. Fully interior solution.',
        pros: ['Fully interior work — no excavation, minimal disruption', 'Applicable to terraced basements or with adjacent buildings', 'Perimeter drainage channel as complementary safety system', 'Compatible with radon — ventilation riser installation integrated'],
        cons: ['Negative system — does not prevent water contacting concrete; manages entry', 'Slight interior space reduction from air cavity (30-50 mm per wall)'],
      },
    ],
    comparison: [
      { feature: 'Durability and service life', epdm: '50+ years without re-intervention', alternatives: [{ name: 'Interior waterproof paint', value: '2-5 years — fails under hydrostatic pressure' }, { name: 'Epoxy resin injection', value: '5-15 years — plugs existing cracks only' }] },
      { feature: 'Hydrostatic pressure effectiveness', epdm: 'Approved at 200 kPa (EN 1928)', alternatives: [{ name: 'Interior waterproof paint', value: 'None — lifts under hydrostatic pressure' }, { name: 'Drainage + sump pump', value: 'Manages water entry (does not stop)' }] },
      { feature: 'Radon gas protection', epdm: 'Effective — BRE 211 / EN 13829 / DGS', alternatives: [{ name: 'Interior waterproof paint', value: 'No effectiveness for radon' }, { name: 'Cementitious crystalline system', value: 'Limited — not a gas barrier' }] },
      { feature: 'Seismic movement accommodation', epdm: '400% elongation — seismic cracking up to 50+ mm', alternatives: [{ name: 'Cementitious crystalline system', value: 'Zero — brittle failure at seismic cracks' }, { name: 'Bentonite GCL', value: 'Limited — seasonal desiccation risk' }] },
      { feature: 'Soil sulphate resistance', epdm: 'Excellent — Classes EA1-EA4 EN 206', alternatives: [{ name: 'Modified bitumen', value: 'Moderate — saponification risk' }, { name: 'Bentonite GCL', value: 'Ion exchange risk in calcareous soils' }] },
      { feature: 'Life-cycle cost (50 years)', epdm: 'Lowest — no replacements', alternatives: [{ name: 'Interior waterproof paint', value: '5-8 re-applications in 50 years' }, { name: 'Drainage + sump pump', value: 'Electricity consumption + pump replacement' }] },
    ],
    climate: [
      { zone: 'Lisbon and Tagus Valley (Alluvial Ground and High Water Table)', description: 'Basements in central Lisbon, Chiado, Almada waterfront and Setúbal have water table at 1-3 m depth in alluvial ground. EPDM approved at 200 kPa (20 m water column) provides 5-10× safety factor over the typical 20-30 kPa design pressures at these locations.' },
      { zone: 'Beira Interior and Trás-os-Montes (Radon)', description: 'Portugal\'s uraniferous granite interior has the highest radon concentrations in continental Europe. EPDM recognised by DGS as a radon retention barrier (BRE 211, EN 13829) is mandatory in basements in these regions — combined with passive sub-slab depressurisation.' },
      { zone: 'Porto and North (Fractured Granite)', description: 'Porto and northern Portugal\'s weathered granite has moderate water table but fractures that conduct water in concentrated flows. EPDM accommodates sudden flow increases at fracture fronts without the localised pressure compromising the membrane — unlike rigid systems.' },
      { zone: 'Coastal Zones (Chlorides and Saline Intrusion)', description: 'Basements in coastal zones (Algarve, Alentejo coast, estuaries) face additional saline intrusion and chloride risk. EPDM is completely inert to salt water and chloride solutions — protecting concrete from attack in tidal or brackish water table environments.' },
      { zone: 'Alentejo and Southern Interior (Expansive Clays)', description: 'Basements founded on Alentejo expansive clay soils face seasonal differential settlement risk (clays expand in wet winter and shrink in dry summer). EPDM 400% elongation accommodates these movements without failure — cementitious systems would crack.' },
    ],
    faqs: [
      { question: 'Does the interior EPDM solution work with high hydrostatic pressure?', answer: 'Yes. The mechanical anchoring system of the internal tanking is designed to resist the specific hydrostatic pressure of each case. EPDM is approved at 200 kPa (20 m water column) per EN 1928 Method A — for a standard basement at 3-5 m depth, the safety factor is 5-20 times.' },
      { question: 'What is the difference between the pre-applied system and internal tanking?', answer: 'The pre-applied (blind-side) system is installed over the excavation support before concrete in new construction — the concrete bonds directly to the membrane. Internal tanking is installed inside the existing basement without excavating — it creates an air cavity between EPDM and wall draining to a perimeter channel. The pre-applied system is more effective; internal tanking is the solution when exterior access is unavailable.' },
      { question: 'Does EPDM protect against radon in geological risk zones?', answer: 'Yes. EPDM is recognised by Portugal\'s DGS and the UK BRE (BRE 211) as an effective radon retention barrier for new construction and rehabilitation. For highest-risk locations (Beira Interior, Trás-os-Montes), Membriko specifies the EPDM membrane combined with a passive sub-slab depressurisation system (geocomposite + ventilation risers), per DGS guidelines and Portaria 353-A/2013.' },
      { question: 'How is the critical slab/wall junction detail treated?', answer: 'The slab-to-wall junction is the highest-risk point in any basement waterproofing. Membriko resolves this with full continuity: the EPDM membrane from the slab folds vertically on the wall with minimum 300 mm width, without a seam at the transition angle. Pre-formed EPDM fillet pieces are bonded at the interior corner to eliminate tensile stress. A single membrane without transverse seam at the highest-risk point.' },
      { question: 'How long does basement waterproofing take?', answer: 'A 50-100 m² basement typically takes 5-10 days of interior work, including preparation, stopping active infiltrations and membrane installation. Without exterior excavation, disruption is minimal. In new construction with pre-applied system, coordination with the main contractor occurs before concreting begins.' },
      { question: 'Does EPDM resist sulphates and aggressive soil chemicals?', answer: 'Yes. EPDM has excellent resistance to sulphates (Exposure Classes EA1-EA4 per EN 206), chlorides, organic acids and petroleum hydrocarbons. For sites with identified contamination (former landfills, fuel stations, industrial zones), Membriko performs chemical compatibility assessment based on the site characterisation report.' },
      { question: 'How is EPDM repaired if damaged by subsequent basement works?', answer: 'Repair by EPDM patch of the same thickness and formulation, bonded with QuickPrime primer and 150 mm QuickSeam tape over the damaged zone, with minimum 75 mm overlap in all directions over clean dry membrane. For damage in zones under concrete or backfill, Membriko performs electric leak detection (ELD) diagnosis before defining the repair strategy.' },
      { question: 'Does EPDM accommodate seismic movements in basements in Lisbon and Algarve?', answer: 'Yes. EPDM 400% elongation accommodates movements of 50+ mm and seismic crack openings of several millimetres — with a safety factor far exceeding any rigid system. For underground structures in Lisbon (Seismic Zone 1.3) and Algarve, Membriko can confirm documentally that the membrane\'s deformation capacity is compatible with the drift values calculated by the structural engineer per Eurocode 8.' },
    ],
    relatedSlugs: ['foundations', 'underground-parking', 'retaining-walls'],
  },
}
