import type { ApplicationData } from '../types'

export const expansionJoints: ApplicationData = {
  id: 'expansion-joints',
  categoryId: 'civil',
  pt: {
    meta: {
      title: 'Impermeabilização de Juntas de Dilatação com EPDM | Membriko',
      description: 'Perfis e membranas EPDM para juntas de dilatação em coberturas, pontes, lajes e fachadas. Estanquidade com movimentos ±75 mm. Sem manutenção. Portugal.',
      keywords: ['impermeabilização junta dilatação EPDM', 'perfil EPDM junta', 'junta dilatação estanque', 'membrana junta movimento', 'EPDM junta estrutural'],
    },
    hero: {
      headline: 'Juntas de Dilatação Estanques com EPDM de Alta Flexibilidade',
      subtitle: 'Perfis e sistemas EPDM para juntas de dilatação garantem estanquidade em movimentos cíclicos de ±75 mm, em coberturas, pontes, lajes e fachadas, sem manutenção por 50+ anos.',
      stats: [
        { value: '±75 mm', label: 'Movimento acomodado' },
        { value: '400%', label: 'Elongação do material' },
        { value: '10.000+', label: 'Ciclos testados sem degradação' },
        { value: '15 anos', label: 'Garantia' },
      ],
    },
    problem: {
      title: 'O Desafio das Juntas de Dilatação',
      description: 'As juntas de dilatação são os pontos mais críticos em qualquer impermeabilização. São necessárias para acomodar movimentos estruturais, mas cada junta é um potencial ponto de infiltração. Mais de 60% das infiltrações em coberturas e lajes ocorrem nas juntas.',
      points: [
        'Movimentos térmicos cíclicos de ±10-75 mm criam fadiga e fratura em materiais de vedação rígidos',
        'Movimentos sísmicos na Zona 1.3 de Lisboa podem atingir 30-50 mm de deslocamento relativo entre blocos',
        'Assentamentos diferenciais progressivos de edifícios de grande porte ampliam os movimentos ao longo de décadas',
        'Soluções inadequadas (silicone, polissulfureto) duram 10-20 anos e perdem elasticidade com o tempo',
      ],
    },
    solution: {
      title: 'A Solução EPDM para Juntas de Dilatação',
      description: 'Os perfis e sistemas de membrana EPDM para juntas de dilatação são especificamente desenvolvidos para acomodar movimentos de grande amplitude de forma duradoura. A elasticidade intrínseca do EPDM — sem plastificantes que migram — elimina a fadiga por ciclos repetidos.',
      points: [
        'Perfis EPDM pré-moldados centre-bulb, gland e waterstop para diferentes amplitudes e aplicações',
        'Método de ansa (loop) com membrana EPDM para movimentos até ±75 mm sem perfil adicional',
        'Vulcanização em obra para ligações monolíticas entre membrana e perfil de junta',
        'Sistemas testados para 10.000+ ciclos de movimento sem degradação por compressão permanente',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Estanquidade Duradoura', description: 'O EPDM mantém estanquidade em juntas com movimentos cíclicos de décadas sem perder elasticidade. O compression set após 22h a 70°C é inferior a 15% (EN ISO 815-1), ao contrário de polissulfureto com compression set de 25-40%.' },
      { icon: 'Layers', title: 'Perfis Pré-Moldados em Fábrica', description: 'Perfis EPDM centre-bulb, gland e waterstop pré-vulcanizados em fábrica garantem geometria perfeita e comportamento previsível em cada tipo de junta. Peças de canto moldadas eliminam soldaduras em campo.' },
      { icon: 'Wrench', title: 'Capacidade de Movimento ±25%', description: 'O EPDM trabalha a ±25% da largura da junta — a maior capacidade de qualquer sistema de selagem. Para uma junta de 50 mm, o EPDM acomoda ±12,5 mm. O polissulfureto acomoda apenas ±6,25 mm na mesma junta.' },
      { icon: 'Thermometer', title: 'Sem Plastificantes que Migram', description: 'A flexibilidade do EPDM é intrínseca à rede de borracha vulcanizada, não depende de plastificantes. Ao contrário de perfis de PVC e neoprene que perdem 20-40% de plastificantes em 15-20 anos em clima português.' },
      { icon: 'Clock', title: 'Sem Manutenção Preventiva', description: 'Ao contrário de silicone (substituição a 10-15 anos), polissulfureto (verificação anual) e PVC (endurecimento progressivo), o EPDM não requer qualquer manutenção preventiva nas juntas durante toda a sua vida útil.' },
      { icon: 'Euro', title: 'Custo Total Mais Baixo em 50 Anos', description: 'O custo inicial do EPDM é superior ao silicone, mas a ausência de substituições (2-3 intervenções de silicone em 50 anos) resulta em custo total de ciclo de vida significativamente inferior.' },
    ],
    specs: [
      { label: 'Amplitude de movimento', value: '±10 mm a ±75 mm (dependente do perfil)' },
      { label: 'Capacidade de trabalho', value: '±25% da largura nominal da junta' },
      { label: 'Número de ciclos testado', value: '> 10.000 ciclos sem degradação' },
      { label: 'Compression set (EN ISO 815-1)', value: '< 15% após 22h a 70°C' },
      { label: 'Temperatura de serviço', value: '-45°C a +130°C' },
      { label: 'Elongação do perfil na rutura', value: '≥ 300%' },
      { label: 'Perfis disponíveis', value: 'Centre-bulb, gland, waterstop, omega, sísmico' },
      { label: 'Norma', value: 'EN 14695 (pontes) / EN 13956 (coberturas)' },
    ],
    installationSteps: [
      { step: 1, title: 'Análise de Movimentos', description: 'Cálculo das amplitudes de movimento por análise térmica (coeficiente de dilatação do betão × comprimento × gama de temperatura) e análise sísmica (Eurocódigo 8, Anexo Nacional). Seleção do perfil adequado para cada junta com fator de segurança 2:1.' },
      { step: 2, title: 'Preparação das Bordas', description: 'Retificação ou jateamento das faces de betão da junta. Resistência de arranque mínima de 0,5 N/mm². Remoção de qualquer vedante existente e resíduos de adesivo incompatível. Limpeza com ar comprimido.' },
      { step: 3, title: 'Aplicação de Primer', description: 'Primer EPDM aplicado nas faces da junta e nas superfícies adjacentes com a largura de colagem prevista (mínimo 100 mm de cada lado). Respeito rigoroso do tempo de flash-off do fabricante — crítico para resistência de adesão.' },
      { step: 4, title: 'Instalação da Membrana Base', description: 'Instalação da membrana EPDM principal até 50 mm de cada lado da junta. Colagem plana e sem bolhas de ar. A zona central sobre o gap da junta não é colada — reserva para movimento.' },
      { step: 5, title: 'Perfil de Junta ou Formação de Ansa', description: 'Colagem do perfil EPDM pré-moldado sobre a junta (método perfil) ou formação da ansa com profundidade = 2 × movimento máximo de extensão (método loop). Peças de canto moldadas em todas as mudanças de direção.' },
      { step: 6, title: 'Vulcanização das Ligações', description: 'Vulcanização a frio nas ligações entre membrana e perfil de junta com adesivo vulcanizante específico. Tira de cobertura EPDM sobre toda a montagem. Reforço em cruzamentos de juntas e cantos.' },
      { step: 7, title: 'Teste e Verificação', description: 'Teste de estanquidade de cada junta por inundação (50 mm de lâmina de água por 24h) ou pressão de ar. Simulação física do movimento — abertura manual à extensão máxima de projeto. Documentação fotográfica e garantia de 15 anos.' },
    ],
    techniques: [
      {
        title: 'Método de Ansa em Membrana EPDM (Movimentos Até ±75 mm)',
        description: 'A membrana EPDM é colada nas bordas da junta e dobrada em ansa (loop) centrada sobre o gap, com profundidade calculada para o movimento de projeto. Para movimentos de grande amplitude incluindo sísmicos. Sistema contínuo sem materiais diferentes.',
        pros: ['Acomoda movimentos muito grandes incluindo sísmicos (±40-75 mm)', 'Continuidade total da membrana — sem interface entre materiais diferentes', 'Adequado para coberturas, pontes e estruturas em zonas sísmicas A e B', 'Margem de segurança 8:1 em extensão máxima com EPDM de 400% de elongação'],
        cons: ['Instalação mais complexa que perfil simples — exige técnico especializado', 'Proteção mecânica específica necessária sobre a ansa em zonas transitáveis'],
      },
      {
        title: 'Perfil Centre-Bulb Pré-Moldado (Movimentos Até ±30 mm)',
        description: 'Perfil EPDM extrudado com bolbo central e flaps de ancoragem. O bolbo funciona como reservatório de material: abre quando a junta dilata, comprime quando fecha. Disponível para juntas de 20 a 150 mm.',
        pros: ['Instalação rápida e precisa — geometria controlada em fábrica', 'Testado em laboratório para amplitudes e cargas definidas', 'Perfis de canto moldados eliminam ligações vulneráveis em campo', 'Versões trafficáveis (gland) para juntas em pavimentos acessíveis'],
        cons: ['Amplitude limitada a ±30 mm em perfil standard (±40-50 mm em grau sísmico)', 'Requer ranhura de ancoragem pré-formada ou cortada mecanicamente na laje'],
      },
      {
        title: 'Perfil Waterstop Embebido em Betão',
        description: 'Perfil EPDM embebido no betão durante a betonagem — as flaps de ancoragem ficam incorporadas em cada elemento de betão. Solução preferida para juntas de estanquidade em estruturas subterrâneas, piscinas e reservatórios.',
        pros: ['Ancoragem mecânica no betão — não depende de adesão de superfície', 'Máxima resistência à pressão hidrostática em juntas enterradas', 'Instalação durante betonagem — sem intervenção subsequente na junta'],
        cons: ['Instalação coordenada com betonagem — impossível de instalar posteriormente', 'Requer posicionamento rigoroso durante cofragem para garantir centramento'],
      },
    ],
    comparison: [
      { feature: 'Vida útil da vedação', epdm: '50+ anos sem substituição', alternatives: [{ name: 'Silicone estrutural', value: '10-15 anos' }, { name: 'Polissulfureto', value: '15-20 anos' }] },
      { feature: 'Capacidade de movimento', epdm: 'Até ±75 mm (sistema ansa)', alternatives: [{ name: 'Silicone estrutural', value: '±25% da largura (máx. ±25 mm)' }, { name: 'Polissulfureto', value: '±12,5% da largura (máx. ±12 mm)' }] },
      { feature: 'Compression set a 70°C', epdm: '< 15% (EN ISO 815-1)', alternatives: [{ name: 'Silicone estrutural', value: '20-30%' }, { name: 'Polissulfureto', value: '25-40%' }] },
      { feature: 'Manutenção preventiva', epdm: 'Nenhuma necessária', alternatives: [{ name: 'Silicone estrutural', value: 'Substituição a 10-15 anos' }, { name: 'Polissulfureto', value: 'Verificação e reperfilagem anual' }] },
      { feature: 'Resistência a sais de degelo', epdm: 'Excelente — inerte a NaCl', alternatives: [{ name: 'Silicone estrutural', value: 'Boa' }, { name: 'Polissulfureto', value: 'Pode sofrer ataque por cloretos' }] },
      { feature: 'Custo de ciclo de vida (50 anos)', epdm: 'Mais baixo — sem intervenções', alternatives: [{ name: 'Silicone estrutural', value: '3-4 substituições em 50 anos' }, { name: 'Polissulfureto', value: '2-3 substituições em 50 anos' }] },
    ],
    climate: [
      { zone: 'Interior Continental (Amplitudes Térmicas Extremas)', description: 'Interior de Portugal com invernos frios (-5°C a -15°C) e verões muito quentes (+35°C a +45°C) cria juntas com movimentos de ±20-40 mm em estruturas de 30 metros. O EPDM acomoda estes movimentos com fator de segurança 8:1 sem fadiga.' },
      { zone: 'Zonas Sísmicas (Lisboa, Setúbal, Algarve)', description: 'Juntas de dilatação em zonas sísmicas devem acomodar movimentos de 30-50 mm de deslocamento relativo (Eurocódigo 8). O EPDM retorna à dimensão nominal após o sismo — vedantes rígidos partem e ficam permanentemente abertos.' },
      { zone: 'Zonas Costeiras (Sal e Humidade)', description: 'Juntas em ambiente marinho sujeitas a sal, névoa salina e ciclos de humedecimento. O EPDM é inerte ao ambiente salino e resiste à hidrólise alcalina do betão (pH 12-13) durante toda a vida útil.' },
      { zone: 'Coberturas de Grande Área (Pavilhões Industriais)', description: 'Coberturas planas de mais de 25-30 metros requerem juntas de dilatação. No Alentejo e Algarve, a amplitude superficial anual de 80-85°C produz movimentos de 25 mm em coberturas de 30 metros. O EPDM dimensionado com ±30% de reserva garante margem adequada.' },
      { zone: 'Beiras e Serra da Estrela (Neve e Gelo)', description: 'Juntas em pavimentos e pontes em zonas de neve expostas a sais de degelo. O EPDM é inerte ao cloreto de sódio e cloreto de cálcio. Os perfis gland trafficáveis mantêm estanquidade mesmo com tráfego de veículos de limpeza de neve.' },
    ],
    faqs: [
      { question: 'Qual a diferença entre perfil de junta pré-moldado e membrana em ansa?', answer: 'O perfil centre-bulb é um elemento extrudado instalado sobre ou na junta, adequado para movimentos até ±30-40 mm. A membrana em ansa usa a própria membrana de impermeabilização dobrada em loop sobre a junta, adequada para movimentos até ±75 mm incluindo sísmicos. A escolha depende da amplitude de movimento calculada e do contexto da obra.' },
      { question: 'O EPDM pode substituir o silicone nas juntas de dilatação existentes?', answer: 'Sim, para juntas em coberturas, lajes, pontes e estruturas subterrâneas. O processo inclui remoção completa do silicone existente (incluindo resíduos de adesivo), preparação das faces e instalação do sistema EPDM adequado. O EPDM tem desempenho muito superior ao silicone em durabilidade, amplitude de movimento e comportamento sísmico.' },
      { question: 'Como se calcula a amplitude de movimento de uma junta de dilatação?', answer: 'O cálculo combina: (1) dilatação térmica = coeficiente de dilatação × comprimento × gama de temperatura; para betão com 10×10⁻⁶/°C, numa laje de 30 m com gama de 75°C, o movimento é 22,5 mm; (2) deslocamento sísmico da análise estrutural conforme Eurocódigo 8; (3) assentamento diferencial estimado. A Membriko realiza este cálculo e seleciona o sistema com fator de segurança de 2:1.' },
      { question: 'Como se repara uma junta EPDM danificada?', answer: 'Reparação por patch de EPDM vulcanizado sobre o dano com adesivo de contacto específico. Se o perfil de junta estiver danificado, substituição do troço danificado por novo perfil soldado com adesivo vulcanizante. A reparação é geralmente possível sem remoção de outros elementos da impermeabilização.' },
      { question: 'O sistema de junta EPDM funciona em juntas sísmicas de edifícios em Lisboa?', answer: 'Sim. Para juntas sísmicas na Zona 1.3 de Lisboa, com movimentos potenciais de 30-50 mm de combinação de abertura e corte, a Membriko especifica o sistema de ansa com profundidade calculada para o deslocamento sísmico de projeto com fator de segurança de 2:1. O EPDM retorna à posição nominal após o evento sísmico, ao contrário de vedantes que partem.' },
      { question: 'Qual o número máximo de ciclos que o sistema EPDM suporta?', answer: 'Os sistemas EPDM são ensaiados para 10.000+ ciclos completos de abertura e fecho sem degradação mensurável. Num edifício com ciclos térmicos diários, 10.000 ciclos representam mais de 27 anos de movimentos diários. Em estruturas com ciclos menos frequentes (sazonais), a vida útil expressa em ciclos excede largamente 100 anos.' },
      { question: 'A instalação de juntas EPDM pode ser feita por cima de uma impermeabilização existente?', answer: 'Depende do estado do suporte. Se a impermeabilização existente está aderida e o vedante antigo foi completamente removido, é possível instalar o sistema EPDM sobre o suporte preparado. Se existem resíduos de silicone ou adesivo incompatível, a remoção total e preparação da superfície são obrigatórias antes da instalação.' },
      { question: 'Qual o custo comparativo entre silicone e EPDM para vedação de juntas de dilatação?', answer: 'O custo inicial do EPDM (perfis ou sistema de ansa) é tipicamente 2-4 vezes superior ao silicone. Contudo, o silicone requer substituição a 10-15 anos — 3-4 intervenções em 50 anos — cada uma com custo de material mais mão de obra de remoção do silicone degradado. Em análise de custo total de 50 anos, o EPDM é invariavelmente mais económico.' },
    ],
    relatedSlugs: ['bridges', 'tunnels', 'plaza-podium'],
  },
  en: {
    meta: {
      title: 'Expansion Joint Waterproofing with EPDM | Membriko',
      description: 'EPDM profiles and membranes for expansion joints in roofs, bridges, slabs and facades. Watertightness with ±75 mm movements. Maintenance-free. Portugal.',
      keywords: ['expansion joint waterproofing EPDM', 'EPDM joint profile', 'watertight expansion joint', 'movement joint membrane', 'EPDM structural joint'],
    },
    hero: {
      headline: 'Watertight Expansion Joints with High-Flexibility EPDM',
      subtitle: 'EPDM profiles and systems for expansion joints guarantee watertightness under cyclic movements of ±75 mm, in roofs, bridges, slabs and facades, maintenance-free for 50+ years.',
      stats: [
        { value: '±75 mm', label: 'Movement accommodated' },
        { value: '400%', label: 'Material elongation' },
        { value: '10,000+', label: 'Cycles tested without degradation' },
        { value: '15 years', label: 'Guarantee' },
      ],
    },
    problem: {
      title: 'The Expansion Joint Challenge',
      description: 'Expansion joints are the most critical points in any waterproofing system. They are needed to accommodate structural movements, but each joint is a potential infiltration point. Over 60% of infiltrations in roofs and slabs occur at joints.',
      points: [
        'Cyclic thermal movements of ±10-75 mm create fatigue and fracture in rigid sealing materials',
        'Seismic movements in Lisbon Zone 1.3 can reach 30-50 mm relative displacement between blocks',
        'Progressive differential settlements in large buildings amplify movements over decades',
        'Inadequate solutions (silicone, polysulphide) last 10-20 years and lose elasticity over time',
      ],
    },
    solution: {
      title: 'The EPDM Solution for Expansion Joints',
      description: 'EPDM profiles and membrane systems for expansion joints are specifically developed to accommodate large-amplitude movements durably. EPDM\'s intrinsic elasticity — without migrating plasticisers — eliminates fatigue from repeated cycles.',
      points: [
        'Pre-moulded EPDM centre-bulb, gland and waterstop profiles for different amplitudes and applications',
        'Loop membrane method with EPDM for movements up to ±75 mm without additional profile',
        'On-site vulcanisation for monolithic connections between membrane and joint profile',
        'Systems tested for 10,000+ movement cycles without permanent compression set degradation',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Lasting Watertightness', description: 'EPDM maintains watertightness in joints under decades of cyclic movements without losing elasticity. Compression set after 22h at 70°C is below 15% (EN ISO 815-1), unlike polysulphide with compression set of 25-40%.' },
      { icon: 'Layers', title: 'Factory Pre-Moulded Profiles', description: 'Factory pre-vulcanised EPDM centre-bulb, gland and waterstop profiles guarantee perfect geometry and predictable behaviour for each joint type. Moulded corner pieces eliminate vulnerable field welds.' },
      { icon: 'Wrench', title: '±25% Movement Capacity', description: 'EPDM works at ±25% of joint width — the largest capacity of any sealing system. For a 50 mm joint, EPDM accommodates ±12.5 mm. Polysulphide accommodates only ±6.25 mm in the same joint.' },
      { icon: 'Thermometer', title: 'No Migrating Plasticisers', description: 'EPDM flexibility is intrinsic to the vulcanised rubber network, not dependent on plasticisers. Unlike PVC and neoprene profiles that lose 20-40% of plasticisers in 15-20 years in Portuguese climate.' },
      { icon: 'Clock', title: 'No Preventive Maintenance', description: 'Unlike silicone (replacement at 10-15 years), polysulphide (annual inspection) and PVC (progressive hardening), EPDM requires no preventive maintenance at joints throughout its service life.' },
      { icon: 'Euro', title: 'Lowest Total Cost over 50 Years', description: 'EPDM initial cost exceeds silicone, but the absence of replacements (2-3 silicone interventions in 50 years) results in significantly lower total life-cycle cost.' },
    ],
    specs: [
      { label: 'Movement amplitude', value: '±10 mm to ±75 mm (profile dependent)' },
      { label: 'Working capacity', value: '±25% of joint nominal width' },
      { label: 'Tested cycle count', value: '> 10,000 cycles without degradation' },
      { label: 'Compression set (EN ISO 815-1)', value: '< 15% after 22h at 70°C' },
      { label: 'Service temperature', value: '-45°C to +130°C' },
      { label: 'Profile elongation at break', value: '≥ 300%' },
      { label: 'Available profiles', value: 'Centre-bulb, gland, waterstop, omega, seismic' },
      { label: 'Standard', value: 'EN 14695 (bridges) / EN 13956 (roofs)' },
    ],
    installationSteps: [
      { step: 1, title: 'Movement Analysis', description: 'Movement amplitude calculation by thermal analysis (concrete thermal expansion coefficient × length × temperature range) and seismic analysis (Eurocode 8, National Annex). Profile selection for each joint with 2:1 safety factor.' },
      { step: 2, title: 'Edge Preparation', description: 'Joint face rectification or blasting. Minimum pull-off resistance 0.5 N/mm². Removal of any existing sealant and incompatible adhesive residues. Compressed air cleaning.' },
      { step: 3, title: 'Primer Application', description: 'EPDM primer applied on joint faces and adjacent surfaces with the planned bonding width (minimum 100 mm each side). Strict observation of manufacturer flash-off time — critical for adhesion strength.' },
      { step: 4, title: 'Base Membrane Installation', description: 'Main EPDM membrane installation to 50 mm either side of joint. Flat bonding without air bubbles. The central zone over the joint gap is not bonded — reserved for movement.' },
      { step: 5, title: 'Joint Profile or Loop Formation', description: 'Pre-moulded EPDM profile bonding over joint (profile method) or loop formation with depth = 2 × maximum extension movement (loop method). Moulded corner pieces at all direction changes.' },
      { step: 6, title: 'Connection Vulcanisation', description: 'Cold vulcanisation at connections between membrane and joint profile with specific vulcanising adhesive. EPDM cover strip over full assembly. Reinforcement at joint crossings and corners.' },
      { step: 7, title: 'Testing and Verification', description: 'Watertightness test of each joint by flooding (50 mm water layer for 24h) or air pressure. Physical movement simulation — manual opening to maximum design extension. Photographic documentation and 15-year warranty.' },
    ],
    techniques: [
      {
        title: 'EPDM Membrane Loop Method (Movements up to ±75 mm)',
        description: 'EPDM membrane bonded on joint edges and folded into a loop centred over the gap, with depth calculated for the design movement. For large-amplitude movements including seismic. Continuous system without different materials.',
        pros: ['Accommodates very large movements including seismic (±40-75 mm)', 'Full membrane continuity — no interface between different materials', 'Suitable for roofs, bridges and structures in seismic zones A and B', '8:1 safety factor at maximum extension with EPDM 400% elongation'],
        cons: ['More complex installation than simple profile — requires specialist technician', 'Specific mechanical protection needed over the loop in trafficked zones'],
      },
      {
        title: 'Pre-Moulded Centre-Bulb Profile (Movements up to ±30 mm)',
        description: 'Extruded EPDM profile with central bulb and anchoring flanges. The bulb acts as material reservoir: opens when the joint dilates, compresses when it closes. Available for joints of 20 to 150 mm.',
        pros: ['Fast and precise installation — factory-controlled geometry', 'Laboratory-tested for defined amplitudes and loads', 'Moulded corner pieces eliminate vulnerable field connections', 'Traffickable versions (gland) for accessible pavement joints'],
        cons: ['Amplitude limited to ±30 mm in standard profile (±40-50 mm in seismic grade)', 'Requires pre-formed or mechanically cut anchoring groove in slab'],
      },
      {
        title: 'Concrete-Cast Waterstop Profile',
        description: 'EPDM profile cast into concrete during pouring — anchoring flanges are incorporated into each concrete element. Preferred solution for watertightness joints in underground structures, pools and reservoirs.',
        pros: ['Mechanical concrete anchorage — not dependent on surface adhesion', 'Maximum hydrostatic pressure resistance in buried joints', 'Installation during pouring — no subsequent joint intervention'],
        cons: ['Coordinated installation with concreting — impossible to install subsequently', 'Requires precise positioning during formwork to guarantee centring'],
      },
    ],
    comparison: [
      { feature: 'Seal service life', epdm: '50+ years without replacement', alternatives: [{ name: 'Structural silicone', value: '10-15 years' }, { name: 'Polysulphide', value: '15-20 years' }] },
      { feature: 'Movement capacity', epdm: 'Up to ±75 mm (loop system)', alternatives: [{ name: 'Structural silicone', value: '±25% of width (max ±25 mm)' }, { name: 'Polysulphide', value: '±12.5% of width (max ±12 mm)' }] },
      { feature: 'Compression set at 70°C', epdm: '< 15% (EN ISO 815-1)', alternatives: [{ name: 'Structural silicone', value: '20-30%' }, { name: 'Polysulphide', value: '25-40%' }] },
      { feature: 'Preventive maintenance', epdm: 'None required', alternatives: [{ name: 'Structural silicone', value: 'Replacement at 10-15 years' }, { name: 'Polysulphide', value: 'Annual inspection and re-profiling' }] },
      { feature: 'De-icing salt resistance', epdm: 'Excellent — inert to NaCl', alternatives: [{ name: 'Structural silicone', value: 'Good' }, { name: 'Polysulphide', value: 'May suffer chloride attack' }] },
      { feature: 'Life-cycle cost (50 years)', epdm: 'Lowest — no interventions', alternatives: [{ name: 'Structural silicone', value: '3-4 replacements in 50 years' }, { name: 'Polysulphide', value: '2-3 replacements in 50 years' }] },
    ],
    climate: [
      { zone: 'Continental Interior (Extreme Thermal Amplitude)', description: 'Portuguese interior with cold winters (-5°C to -15°C) and very hot summers (+35°C to +45°C) creates joints with ±20-40 mm movements in 30-metre structures. EPDM accommodates these movements with 8:1 safety factor without fatigue.' },
      { zone: 'Seismic Zones (Lisbon, Setúbal, Algarve)', description: 'Expansion joints in seismic zones must accommodate 30-50 mm relative displacement (Eurocode 8). EPDM returns to its nominal dimension after the earthquake — rigid sealants fracture and remain permanently open.' },
      { zone: 'Coastal Zones (Salt and Humidity)', description: 'Joints in marine environments subject to salt, sea spray and wetting cycles. EPDM is inert to the saline environment and resists alkaline hydrolysis of concrete (pH 12-13) throughout its service life.' },
      { zone: 'Large-Area Roofs (Industrial Buildings)', description: 'Flat roofs exceeding 25-30 metres require expansion joints. In Alentejo and Algarve, the annual surface amplitude of 80-85°C produces 25 mm movement in 30-metre roofs. EPDM sized with ±30% reserve provides adequate margin.' },
      { zone: 'Beiras and Serra da Estrela (Snow and Ice)', description: 'Joints in pavements and bridges in snow zones exposed to de-icing salts. EPDM is inert to sodium chloride and calcium chloride. Traffickable gland profiles maintain watertightness even under snow-ploughing vehicle traffic.' },
    ],
    faqs: [
      { question: 'What is the difference between a pre-moulded joint profile and a membrane loop?', answer: 'The centre-bulb profile is an extruded element installed over or in the joint, suitable for movements up to ±30-40 mm. The membrane loop uses the waterproofing membrane itself folded over the joint, suitable for movements up to ±75 mm including seismic. The choice depends on the calculated movement amplitude and project context.' },
      { question: 'Can EPDM replace silicone in existing expansion joints?', answer: 'Yes, for joints in roofs, slabs, bridges and underground structures. The process includes complete removal of existing silicone (including adhesive residues), face preparation and installation of the appropriate EPDM system. EPDM has far superior performance to silicone in durability, movement amplitude and seismic behaviour.' },
      { question: 'How is expansion joint movement amplitude calculated?', answer: 'The calculation combines: (1) thermal expansion = expansion coefficient × length × temperature range; for concrete with 10×10⁻⁶/°C, in a 30 m slab with 75°C range, movement is 22.5 mm; (2) seismic displacement from structural analysis per Eurocode 8; (3) estimated differential settlement. Membriko performs this calculation and selects the system with a 2:1 safety factor.' },
      { question: 'How is a damaged EPDM joint repaired?', answer: 'Repair by vulcanised EPDM patch over the damage with specific contact adhesive. If the joint profile is damaged, replacement of the damaged section by welding in a new profile with vulcanising adhesive. Repair is generally possible without removing other waterproofing elements.' },
      { question: 'Does the EPDM joint system work for seismic joints in Lisbon buildings?', answer: 'Yes. For seismic joints in Lisbon Zone 1.3, with potential movements of 30-50 mm combining opening and shear, Membriko specifies the loop system with depth calculated for the design seismic displacement with 2:1 safety factor. EPDM returns to nominal position after the seismic event, unlike sealants that fracture.' },
      { question: 'What is the maximum number of cycles the EPDM system withstands?', answer: 'EPDM systems are tested for 10,000+ complete opening and closing cycles without measurable degradation. In a building with daily thermal cycles, 10,000 cycles represents over 27 years of daily movements. In structures with less frequent cycles (seasonal), service life expressed in cycles far exceeds 100 years.' },
      { question: 'Can EPDM joint installation be done over an existing waterproofing?', answer: 'Depends on substrate condition. If existing waterproofing is bonded and old sealant has been fully removed, EPDM system can be installed over the prepared substrate. If silicone or incompatible adhesive residues are present, complete removal and surface preparation are mandatory before installation.' },
      { question: 'What is the cost comparison between silicone and EPDM for expansion joint sealing?', answer: 'EPDM initial cost (profiles or loop system) is typically 2-4 times higher than silicone. However, silicone requires replacement at 10-15 years — 3-4 interventions in 50 years — each with material cost plus labour for removing degraded silicone. In 50-year total cost analysis, EPDM is invariably more economical.' },
    ],
    relatedSlugs: ['bridges', 'tunnels', 'plaza-podium'],
  },
}
