import type { ApplicationData } from '../types'

export const plazaPodium: ApplicationData = {
  id: 'plaza-podium',
  categoryId: 'civil',
  pt: {
    meta: {
      title: 'Impermeabilização de Plataformas e Pódios com EPDM | Membriko',
      description: 'Membrana EPDM para lajes de plataformas sobre edifícios, pódios e terraços com uso público. Resistência a raízes (EN 13948/FLL), tráfego e pressão hidrostática. Portugal.',
      keywords: ['impermeabilização plataforma EPDM', 'podium impermeabilização', 'laje sobre garagem impermeável', 'terraço público impermeabilização', 'plaza deck EPDM'],
    },
    hero: {
      headline: 'Plataformas e Pódios Impermeáveis com EPDM de Alta Performance',
      subtitle: 'Impermeabilize lajes de plataformas sobre estacionamentos, coberturas de edifícios com uso pedonal e jardins sobre laje com EPDM — certificado FLL anti-raiz e vida útil de 50+ anos.',
      stats: [
        { value: '50+', label: 'Anos de vida útil' },
        { value: '2,0 mm', label: 'Espessura com certificação FLL' },
        { value: '400%', label: 'Elongação para movimentos de junta' },
        { value: '20 anos', label: 'Garantia' },
      ],
    },
    problem: {
      title: 'O Desafio das Plataformas e Pódios',
      description: 'As plataformas sobre edifícios e pódios combinam múltiplas exigências numa só estrutura: impermeabilização, resistência a raízes, cargas variáveis, drenagem eficiente e coexistência de jardins, espaços pedonais e tráfego de serviço sobre a mesma laje.',
      points: [
        'Raízes de árvores e arbustos penetram membranas sem certificação FLL em 5-10 anos — a reparação exige remoção total do jardim',
        'Juntas de dilatação entre blocos estruturais são o ponto de maior risco — movimentos de ±15-25 mm em ciclos sazonais',
        'Falhas na impermeabilização causam danos catastróficos nos estacionamentos, espaços comerciais e habitações nos pisos inferiores',
        'Membranas líquidas de PU necessitam re-revestimento ao ano 10-15 — com remoção do jardim — custo 5-10 vezes superior à instalação original',
      ],
    },
    solution: {
      title: 'A Solução EPDM para Plataformas',
      description: 'O sistema EPDM para plataformas e pódios combina impermeabilização de 50+ anos, resistência intrínseca à penetração de raízes (EN 13948/FLL sem biocidas) e compatibilidade com múltiplos usos de superfície. O sistema é dimensionado para o uso previsto em cada zona.',
      points: [
        'EPDM 2,0 mm com certificação EN 13948/FLL anti-raiz intrínseca — sem herbicidas que migram para a drenagem',
        'Sistema completo com ensaio de inundação 100% da área antes de qualquer cobertura',
        'Tampas de junta de dilatação prefabricadas em EPDM com folga calculada para ±20 mm',
        'Compatibilidade com jardim intensivo, pavimento pedonal, gravilha, esplanada ou acesso de serviço na mesma laje',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Anti-Raiz Certificado (EN 13948/FLL)', description: 'O EPDM passa o ensaio FLL de 24 meses com Agropyron repens e Quercus robur sem qualquer perfuração — sem biocidas. Ao contrário do PVC (herbicidas mecoprop) e do betume SBS (necessita folha de HDPE separada).' },
      { icon: 'Layers', title: 'Usos Múltiplos na Mesma Laje', description: 'Sistema adaptável para pódio multi-zona: jardins intensivos com árvores, espaços pedonais, esplanadas comerciais, acesso de veículos de serviço — tudo com uma membrana EPDM contínua e transições monolíticas entre zonas.' },
      { icon: 'Droplets', title: 'Drenagem Multi-Nível', description: 'O sistema EPDM inclui drenos primários com flange EPDM integrada, descargas de emergência secundárias e drenos de fossa de árvore perimetrais — dimensionados para intensidades de precipitação de 60-100 L/s/ha conforme EN 12056-3.' },
      { icon: 'Wrench', title: 'Ensaio de Inundação 100%', description: 'A Membriko realiza ensaio de inundação de 100% da área instalada (50 mm de lâmina de água por 24h) antes de qualquer camada de proteção, sistema drenante ou substrato — documentado fotograficamente.' },
      { icon: 'Euro', title: 'Custo Total Mais Baixo em 30 Anos', description: 'O custo do EPDM é superior ao PU líquido no ato de instalação. Mas o PU necessita re-revestimento ao ano 10-15 com remoção do jardim — custo 5-10 vezes superior ao diferencial inicial. Em 30 anos, o EPDM é a escolha economicamente defensável.' },
      { icon: 'Clock', title: 'Vida Útil Superior ao Ciclo dos Revestimentos', description: 'O EPDM instalado num pódio tem vida útil de 50+ anos (ERA 30-Year Study; SKZ Durability Study). Excede o ciclo de renovação de jardins (20-30 anos) e pavimentos (20-40 anos). A membrana nunca é o motivo de uma intervenção no espaço público.' },
    ],
    specs: [
      { label: 'Espessura (zona pedonal)', value: '1,5 mm (EN 1849-2)' },
      { label: 'Espessura (jardim/veicular)', value: '2,0 mm (EN 1849-2)' },
      { label: 'Resistência à penetração radicular', value: 'Passa EN 13948 / FLL — certificado' },
      { label: 'Elongação na rutura', value: '≥ 300% (1,5 mm) / ≥ 400% (2,0 mm)' },
      { label: 'Temperatura de serviço', value: '-45°C a +150°C' },
      { label: 'Resistência química (fertilizantes, pesticidas)', value: 'Inerte — pH 4 a 12' },
      { label: 'Pendente mínima para drenos', value: '1,5% (zonas ajardinadas) / 1,0% (pavimentadas)' },
      { label: 'Norma de produto', value: 'EN 13956 Tipo 3 (marcação CE)' },
    ],
    installationSteps: [
      { step: 1, title: 'Coordenação Integrada de Projeto', description: 'Entrada no projeto na fase de anteprojeto em coordenação com engenheiro de estruturas, arquiteto paisagista e projetista de instalações. Definição de zonas de uso, cargas, localização de drenos, juntas de dilatação e alturas de platibandas.' },
      { step: 2, title: 'Levantamento e Preparação da Laje', description: 'Inspeção da laje: fissuras > 0,3 mm tratadas com resina epóxi por injeção. Laitância superficial removida — resistência ao arranque mínima 0,8 N/mm² (EN 12188). Pendentes verificadas: mínimo 1,5% para drenos em zonas ajardinadas.' },
      { step: 3, title: 'Drenos e Dispositivos Singulares', description: 'Todos os drenos instalados e ligados ao sistema de escoamento antes do início da membrana. Flanges de drenagem posicionadas à cota correta para integração com a camada drenante. Perfis de junta de dilatação posicionados e fixados.' },
      { step: 4, title: 'Instalação da Membrana EPDM', description: 'Folhas únicas de grande dimensão (até 15,25 m × 61 m) para minimizar costuras. Sobreposições mínimas de 75 mm com inspeção visual e de pressão de 100% das costuras. Pontos singulares — ralos, platibandas, juntas, tubagens — com acessórios prefabricados EPDM.' },
      { step: 5, title: 'Ensaio de Inundação (100% da Área)', description: '100% da área de membrana sujeita a ensaio de inundação com 50 mm de lâmina de água por mínimo de 24 horas. Qualquer anomalia leva a identificação, correção e re-ensaio. Resultado documentado fotograficamente.' },
      { step: 6, title: 'Proteção e Drenagem', description: 'Imediatamente após validação do ensaio: instalação de geotêxtil de proteção 300-500 g/m². Coordenação com empreiteiros do sistema drenante, substrato e pavimento para garantir sequência correta sem danificar a membrana.' },
      { step: 7, title: 'Substrato, Pavimento e Garantia', description: 'Instalação de substrato mineral de jardim (não terra vegetal), betão de proteção, gravilha decorativa ou pavimento pedonal conforme uso previsto em cada zona. Entrega do dossier com planta as-built, certificado de inundação e garantia de 20 anos.' },
    ],
    techniques: [
      {
        title: 'Sistema Jardim sobre Laje Intensivo (Green Plaza)',
        description: 'EPDM 2,0 mm com certificação EN 13948/FLL + geotêxtil de proteção + camada drenante (placa HDPE ou agregado) + geotêxtil de filtração + substrato mineral. Para plataformas com árvores (substrato 600-1.200 mm) e arbustos (substrato 300-600 mm).',
        pros: ['Certificação anti-raiz intrínseca para árvores e arbustos sem herbicidas', 'Sistema de drenagem multi-nível com drenos de fossa de árvore perimetrais', 'Retenção de 50-70% do volume de precipitação — mitigação do efeito de ilha de calor', 'Vida útil de 50+ anos — membrana nunca requer remoção do jardim para manutenção'],
        cons: ['Sistema mais complexo com várias camadas e coordenação integrada', 'Peso saturado de 4-8 kN/m² — verificação estrutural obrigatória para o total de cargas'],
      },
      {
        title: 'Sistema Pedonal e Comercial (Urban Plaza)',
        description: 'EPDM 1,5-2,0 mm + geotêxtil de proteção + betão de proteção 50-75 mm + pavimento pedonal (pedra natural, cerâmica, betuminoso drenante). Para praças e espaços públicos sobre laje sem jardim intensivo.',
        pros: ['Sistema mais leve que jardim intensivo — menor carga na estrutura', 'Pedra natural, granito ou calcário português em acabamento de qualidade', 'Manutenção simplificada sem rega, substrato ou sistema drenante de jardim'],
        cons: ['Sem benefício de cobertura vegetal e gestão de águas pluviais', 'Juntas de dilatação no pavimento a cada 3 m para cerâmica — coordenação necessária'],
      },
      {
        title: 'Sistema Tráfego de Serviço (Vehicular Plaza)',
        description: 'EPDM 2,0 mm + geotêxtil + betão armado de distribuição de cargas (mínimo 100 mm, C25/30, malha de armadura) dimensionado para eixos até 3,5 t. Para zonas de acesso de veículos de serviço, ambulâncias e camiões de abastecimento.',
        pros: ['Compatível com veículos de serviço correntes até 3,5 t por eixo', 'Laje de betão armado distribui cargas pontuais sobre a membrana EPDM', 'Solução que coexiste com zonas pedonais e de jardim na mesma laje'],
        cons: ['Veículos mais pesados requerem revisão de engenharia estrutural', 'Instalação coordenada com estrutural — carga acrescida de 2,5 kN/m² ou mais'],
      },
    ],
    comparison: [
      { feature: 'Resistência radicular (certificação)', epdm: 'FLL / EN 13948 — intrínseca, sem biocidas', alternatives: [{ name: 'PVC para jardim', value: 'Herbicidas mecoprop — migram para drenagem' }, { name: 'Betume SBS', value: 'Não certificado sem folha HDPE separada' }] },
      { feature: 'Vida útil', epdm: '50+ anos (ERA/SKZ studies)', alternatives: [{ name: 'PU líquido', value: '10-20 anos (re-revestimento ao ano 10-15)' }, { name: 'Betume SBS', value: '15-25 anos' }] },
      { feature: 'Intervenção a meio de vida', epdm: 'Nenhuma necessária (50+ anos)', alternatives: [{ name: 'PU líquido', value: 'Re-revestimento exige remoção do jardim' }, { name: 'Betume SBS', value: 'Substituição ao ano 15-25' }] },
      { feature: 'Resistência química (agroquímicos)', epdm: 'Inerte a fertilizantes, pesticidas, pH 4-12', alternatives: [{ name: 'PU líquido', value: 'Pode degradar com exposição a agroquímicos' }, { name: 'Betume SBS', value: 'Estável, mas solventes durante instalação' }] },
      { feature: 'Acomodação juntas de dilatação', epdm: 'Tampas prefabricadas ≥ ±20 mm', alternatives: [{ name: 'PU líquido', value: 'Tipicamente 5-10 mm (mástique)' }, { name: 'Betume SBS', value: '10-15 mm com detalhe em ansa' }] },
      { feature: 'Custo total 30 anos', epdm: 'Mais baixo — sem intervenções', alternatives: [{ name: 'PU líquido', value: 'Mais alto — re-revestimento + remoção jardim' }, { name: 'Betume SBS', value: 'Alto — substituição + reinstalação' }] },
    ],
    climate: [
      { zone: 'Lisboa e Porto (Jardins Urbanos, PRR)', description: 'O PRR e fundos de coesão impulsionam renovação urbana com praças sobre estacionamentos e caves técnicas. O crescimento rápido de vegetação em clima temperado exige certificação FLL robusta. O EPDM 2,0 mm resiste a raízes de árvores de crescimento agressivo comuns em pódios urbanos portugueses.' },
      { zone: 'Algarve (Calor Intenso e Rega Frequente)', description: 'Temperaturas superficiais de praças expostas atingem 70-80°C no verão no Algarve. O EPDM é estável a -45°C a +150°C e quimicamente inerte a fertilizantes e pesticidas de rega em clima mediterrânico. Os hotéis e empreendimentos turísticos do Algarve são os principais beneficiários.' },
      { zone: 'Norte Atlântico (Precipitação e Caudais Elevados)', description: 'Precipitação de 60-80 L/s/ha (período de retorno 10 anos) no Minho exige drenagem eficiente. O sistema EPDM com camada drenante e drenos de emergência secundários é dimensionado para estes caudais conforme EN 12056-3.' },
      { zone: 'Campus Universitários e Complexos Corporativos', description: 'Renovação de parques de estacionamento cobertos com terraços e jardins em campus universitários (Coimbra, Aveiro, Braga). O EPDM suporta instalações de rega, condutas técnicas e eventos públicos sobre a mesma laje sem manutenção da membrana.' },
      { zone: 'Frentes Fluviais (Lisboa, Porto, Coimbra)', description: 'Praças ribeirinhas sobre caves técnicas e estacionamentos (Parque das Nações, Alcântara, Ribeira de Porto) com nível freático variável. O EPDM resistente a pressão hidrostática e ao ambiente húmido é a solução de referência para estas localizações.' },
    ],
    faqs: [
      { question: 'O EPDM resiste às raízes de árvores grandes em jardins sobre laje?', answer: 'Sim, o EPDM 2,0 mm com certificação EN 13948/FLL é o padrão europeu de resistência a raízes. O ensaio FLL expõe a membrana a Agropyron repens e Quercus robur por 24 meses — o EPDM passa sem qualquer perfuração, sem biocidas. Para árvores de porte em valas profundas, a Membriko especifica também drenagem perimetral de fossa de árvore para evitar concentração radicular na membrana.' },
      { question: 'Como se trata a junta de dilatação entre dois blocos de betão numa plataforma?', answer: 'A Membriko utiliza tampas de junta de dilatação prefabricadas em EPDM com folga projetada para a amplitude de movimento calculada — tipicamente ±15-20 mm para as condições climáticas portuguesas. A tampa é colada nas duas abas à membrana de campo com sobreposição mínima de 150 mm de cada lado. Não se utilizam cordões de mástique — a vedação é garantida pelo próprio EPDM vulcanizado.' },
      { question: 'Qual o teste que confirma a estanquidade antes de cobrir a membrana?', answer: 'A Membriko realiza ensaio de inundação em 100% da área instalada antes de qualquer camada de proteção ou substrato. O ensaio mantém 50 mm de lâmina de água por mínimo de 24 horas. Qualquer fuga é localizada, reparada e sujeita a re-ensaio. O resultado é documentado fotograficamente e incluído no dossier de entrega com o certificado de garantia.' },
      { question: 'O EPDM resiste aos produtos de rega e adubação usados nos jardins sobre laje?', answer: 'Sim. O EPDM é quimicamente inerte à totalidade dos agroquímicos utilizados em irrigação ornamental: adubos NPK de alta concentração, pesticidas, fungicidas, herbicidas e corretores de pH (sulfonato de alumínio, carbonato de cálcio). Esta inertidade é intrínseca à química do polímero EPDM — não se degrada com o tempo.' },
      { question: 'Posso ter veículos de serviço na mesma plataforma que o jardim?', answer: 'Sim, com zonamento correto. A zona de tráfego usa EPDM + betão armado de distribuição de cargas (≥100 mm, C25/30). A zona de jardim usa EPDM + drenante + substrato. A transição entre zonas é tratada com detalhe monolítico EPDM. Cargas por eixo até 3,5 t são compatíveis — veículos mais pesados requerem revisão estrutural.' },
      { question: 'Pode instalar-se EPDM sobre uma impermeabilização de betume existente num pódio em reabilitação?', answer: 'Sim, sujeito a avaliação do estado do suporte. Se a membrana betuminosa existente está aderida e sem bolhas, o EPDM pode ser colado com primer compatível. Se apresenta delaminação ou degradação química, é necessária remoção total. A Membriko realiza ensaio de arranque (EN 12188) e termografia de infravermelhos por drone para localização de zonas húmidas antes de confirmar o método de reabilitação.' },
      { question: 'Como se drena um jardim sobre laje numa plataforma?', answer: 'O sistema multi-nível inclui: pendentes na laje (min 1,5%), membrana EPDM, geotêxtil de proteção, camada drenante (placa HDPE ou Leca 20-40 mm), geotêxtil de filtração, substrato mineral. Drenos primários penetram todas as camadas até à membrana. Descargas de emergência secundárias 50 mm acima dos drenos primários. Cada vala de árvore tem anel drenante perimetral ligado à camada drenante principal.' },
      { question: 'Qual o impacte ambiental do EPDM comparado com membranas líquidas de poliuretano?', answer: 'O EPDM tem carbono incorporado por ano de vida útil inferior ao PU líquido quando o ciclo de substituição do PU é incluído. O EPDM não contém cloro (ao contrário do PVC), não necessita de biocidas para resistência radicular, e é reciclável no fim de vida. Para projetos com certificação BREEAM Mat 05 ou LEED v4 MR, a Membriko fornece EPD (Declaração Ambiental de Produto) dos materiais instalados.' },
      { question: 'Quanto tempo dura uma impermeabilização EPDM numa praça urbana sem manutenção?', answer: 'Dados do ERA 30-Year Field Study (EUA) e do estudo de durabilidade SKZ (Alemanha) demonstram vida útil superior a 50 anos. Numa plataforma, a membrana está protegida da radiação UV e de impacto mecânico pelas camadas sobrepostas — a vida útil esperada é ainda superior à de instalações expostas. A garantia da Membriko de 20 anos representa o mínimo garantido; a vida útil de projeto é o horizonte de vida do edifício.' },
    ],
    relatedSlugs: ['green-roofs', 'underground-parking', 'expansion-joints'],
  },
  en: {
    meta: {
      title: 'Plaza and Podium Deck Waterproofing with EPDM | Membriko',
      description: 'EPDM membrane for plaza slabs over buildings, podium decks and public-use terraces. Root resistance (EN 13948/FLL), traffic and hydrostatic pressure. Portugal.',
      keywords: ['plaza waterproofing EPDM', 'podium deck waterproofing', 'slab over garage waterproofing', 'public terrace waterproofing', 'plaza deck EPDM'],
    },
    hero: {
      headline: 'Waterproof Plazas and Podium Decks with High-Performance EPDM',
      subtitle: 'Waterproof plaza slabs over car parks, building rooftops with pedestrian use and roof gardens with EPDM — FLL root-resistance certified and 50+ years service life.',
      stats: [
        { value: '50+', label: 'Years service life' },
        { value: '2.0 mm', label: 'FLL-certified thickness' },
        { value: '400%', label: 'Elongation for joint movement' },
        { value: '20 years', label: 'Guarantee' },
      ],
    },
    problem: {
      title: 'The Plaza and Podium Deck Challenge',
      description: 'Plazas over buildings and podium decks combine multiple demands in one structure: waterproofing, root resistance, variable loads, efficient drainage, and coexistence of gardens, pedestrian spaces and service vehicle access on the same slab.',
      points: [
        'Tree and shrub roots penetrate membranes without FLL certification within 5-10 years — repair requires full garden removal',
        'Expansion joints between structural blocks are the highest-risk point — movements of ±15-25 mm in seasonal cycles',
        'Waterproofing failures cause catastrophic damage to car parks, commercial spaces and residences on lower floors',
        'Liquid PU membranes require re-coating at year 10-15 — with garden removal — cost 5-10 times the original installation',
      ],
    },
    solution: {
      title: 'The EPDM Solution for Plaza Decks',
      description: 'The EPDM system for plazas and podium decks combines 50+ year waterproofing, intrinsic root penetration resistance (EN 13948/FLL without biocides) and compatibility with multiple surface uses. The system is sized for the intended use in each zone.',
      points: [
        '2.0 mm EPDM with intrinsic EN 13948/FLL root resistance — without herbicides that migrate into drainage water',
        'Complete system with 100% flood test before any covering layer',
        'Pre-fabricated EPDM expansion joint covers with calculated slack for ±20 mm',
        'Compatibility with intensive garden, pedestrian paving, gravel, restaurant terrace or service access on same slab',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Certified Root Resistance (EN 13948/FLL)', description: 'EPDM passes the 24-month FLL test with Agropyron repens and Quercus robur without any puncture — without biocides. Unlike PVC (mecoprop herbicides) and SBS bitumen (requires separate HDPE sheet).' },
      { icon: 'Layers', title: 'Multiple Uses on Same Slab', description: 'Adaptable system for multi-zone podium: intensive gardens with trees, pedestrian spaces, commercial terraces, service vehicle access — all with one continuous EPDM membrane and monolithic transitions between zones.' },
      { icon: 'Droplets', title: 'Multi-Level Drainage', description: 'The EPDM system includes primary drains with integrated EPDM flange, secondary emergency overflows and perimeter tree pit drains — sized for rainfall intensities of 60-100 L/s/ha per EN 12056-3.' },
      { icon: 'Wrench', title: '100% Flood Test', description: 'Membriko performs a flood test of 100% of the installed area (50 mm water layer for 24h) before any protection layer, drainage system or substrate — photographically documented.' },
      { icon: 'Euro', title: 'Lowest Total Cost over 30 Years', description: 'EPDM has higher initial cost than liquid PU. But PU requires re-coating at year 10-15 with garden removal — 5-10 times the cost differential. Over 30 years, EPDM is the economically defensible choice.' },
      { icon: 'Clock', title: 'Service Life Exceeds Surfacing Renewal Cycle', description: 'EPDM installed on a podium has 50+ year service life (ERA 30-Year Study; SKZ Durability Study). This exceeds garden renovation cycles (20-30 years) and paving (20-40 years). The membrane is never the reason for a public space intervention.' },
    ],
    specs: [
      { label: 'Thickness (pedestrian zone)', value: '1.5 mm (EN 1849-2)' },
      { label: 'Thickness (garden/vehicular)', value: '2.0 mm (EN 1849-2)' },
      { label: 'Root penetration resistance', value: 'Passes EN 13948 / FLL — certified' },
      { label: 'Elongation at break', value: '≥ 300% (1.5 mm) / ≥ 400% (2.0 mm)' },
      { label: 'Service temperature', value: '-45°C to +150°C' },
      { label: 'Chemical resistance (fertilisers, pesticides)', value: 'Inert — pH 4 to 12' },
      { label: 'Minimum slope to drains', value: '1.5% (landscaped zones) / 1.0% (paved)' },
      { label: 'Product standard', value: 'EN 13956 Type 3 (CE marking)' },
    ],
    installationSteps: [
      { step: 1, title: 'Integrated Design Coordination', description: 'Entry into design at concept stage in coordination with structural engineer, landscape architect and services designer. Definition of use zones, loads, drain locations, expansion joints and parapet heights.' },
      { step: 2, title: 'Slab Survey and Preparation', description: 'Slab inspection: cracks >0.3 mm treated with epoxy injection. Surface laitance removed — minimum pull-off resistance 0.8 N/mm² (EN 12188). Slopes verified: minimum 1.5% to drains in landscaped zones.' },
      { step: 3, title: 'Drains and Singular Devices', description: 'All drains installed and connected to building drainage system before membrane work begins. Drain flanges positioned at correct level for integration with planned drainage layer. Expansion joint profiles positioned and fixed.' },
      { step: 4, title: 'EPDM Membrane Installation', description: 'Single large sheets (up to 15.25 m × 61 m) to minimise field seams. Minimum 75 mm overlaps with 100% visual and pressure inspection of all seams. Singular points — drains, parapets, joints, pipework — with prefabricated EPDM accessories.' },
      { step: 5, title: 'Flood Test (100% of Area)', description: '100% of membrane area subjected to flood test with 50 mm water layer for minimum 24 hours. Any anomaly leads to identification, correction and re-test. Result photographically documented.' },
      { step: 6, title: 'Protection and Drainage', description: 'Immediately after flood test validation: protective geotextile 300-500 g/m² installation. Coordination with drainage, substrate and paving contractors to ensure correct sequence without damaging the membrane.' },
      { step: 7, title: 'Substrate, Paving and Warranty', description: 'Mineral garden substrate (not topsoil), protection concrete, decorative gravel or pedestrian paving installation per intended use in each zone. Delivery of dossier with as-built plan, flood test certificate and 20-year warranty.' },
    ],
    techniques: [
      {
        title: 'Intensive Roof Garden System (Green Plaza)',
        description: '2.0 mm EN 13948/FLL-certified EPDM + protective geotextile + drainage layer (HDPE plate or aggregate) + filter geotextile + mineral substrate. For platforms with trees (substrate 600-1,200 mm) and shrubs (substrate 300-600 mm).',
        pros: ['Intrinsic root resistance certification for trees and shrubs without herbicides', 'Multi-level drainage with perimeter tree pit drains', 'Retention of 50-70% of rainfall volume — urban heat island mitigation', 'Service life 50+ years — membrane never requires garden removal for maintenance'],
        cons: ['More complex multi-layer system requiring integrated coordination', 'Saturated weight 4-8 kN/m² — mandatory structural check for total loads'],
      },
      {
        title: 'Pedestrian and Commercial System (Urban Plaza)',
        description: '1.5-2.0 mm EPDM + protective geotextile + 50-75 mm protection concrete + pedestrian paving (natural stone, ceramic, porous asphalt). For plazas and public spaces over slab without intensive garden.',
        pros: ['Lighter system than intensive garden — lower structural load', 'Portuguese natural stone, granite or limestone as quality finish', 'Simplified maintenance without irrigation, substrate or garden drainage system'],
        cons: ['No vegetation cover benefit and stormwater management', 'Expansion joints in ceramic paving every 3 m — coordination required'],
      },
      {
        title: 'Service Traffic System (Vehicular Plaza)',
        description: '2.0 mm EPDM + geotextile + reinforced load-distributing concrete slab (minimum 100 mm, C25/30, reinforcement mesh) designed for axle loads up to 3.5 t. For service vehicle, ambulance and delivery truck access zones.',
        pros: ['Compatible with common service vehicles up to 3.5 t per axle', 'Reinforced concrete distributes point loads over EPDM membrane', 'Solution coexisting with pedestrian and garden zones on same slab'],
        cons: ['Heavier vehicles require structural engineering review', 'Coordinated structural design — additional load of 2.5 kN/m² or more'],
      },
    ],
    comparison: [
      { feature: 'Root resistance (certification)', epdm: 'FLL / EN 13948 — intrinsic, no biocides', alternatives: [{ name: 'PVC for garden', value: 'Mecoprop herbicides — migrate into drainage' }, { name: 'SBS bitumen', value: 'Not certified without separate HDPE sheet' }] },
      { feature: 'Service life', epdm: '50+ years (ERA/SKZ studies)', alternatives: [{ name: 'Liquid PU', value: '10-20 years (re-coating at year 10-15)' }, { name: 'SBS bitumen', value: '15-25 years' }] },
      { feature: 'Mid-life intervention', epdm: 'None required (50+ years)', alternatives: [{ name: 'Liquid PU', value: 'Re-coating requires full garden removal' }, { name: 'SBS bitumen', value: 'Replacement at year 15-25' }] },
      { feature: 'Chemical resistance (agrochemicals)', epdm: 'Inert to fertilisers, pesticides, pH 4-12', alternatives: [{ name: 'Liquid PU', value: 'May degrade with agrochemical exposure' }, { name: 'SBS bitumen', value: 'Stable, but solvents during installation' }] },
      { feature: 'Expansion joint accommodation', epdm: 'Pre-fabricated covers ≥ ±20 mm', alternatives: [{ name: 'Liquid PU', value: 'Typically 5-10 mm (mastic sealant)' }, { name: 'SBS bitumen', value: '10-15 mm with loop detail' }] },
      { feature: 'Total cost over 30 years', epdm: 'Lowest — no interventions', alternatives: [{ name: 'Liquid PU', value: 'Highest — re-coating + garden removal' }, { name: 'SBS bitumen', value: 'High — replacement + reinstallation' }] },
    ],
    climate: [
      { zone: 'Lisbon and Porto (Urban Gardens, PRR Funding)', description: 'Portugal\'s Recovery and Resilience Plan drives urban renewal with plazas over car parks and technical basements. Rapid vegetation growth in temperate climate demands robust FLL certification. EPDM 2.0 mm resists aggressively growing tree roots common in Portuguese urban podiums.' },
      { zone: 'Algarve (Intense Heat and Frequent Irrigation)', description: 'Surface temperatures of exposed plazas reach 70-80°C in summer in Algarve. EPDM is stable from -45°C to +150°C and chemically inert to fertilisers and pesticides used in Mediterranean climate irrigation. Hotels and tourist developments are the primary beneficiaries.' },
      { zone: 'Atlantic North (High Rainfall and Flows)', description: 'Rainfall of 60-80 L/s/ha (10-year return period) in Minho demands efficient drainage. The EPDM system with drainage layer and secondary emergency overflows is sized for these flows per EN 12056-3.' },
      { zone: 'University Campuses and Corporate Complexes', description: 'Renewal of covered car parks with terraces and gardens at university campuses (Coimbra, Aveiro, Braga). EPDM supports irrigation installations, technical conduits and public events on the same slab without membrane maintenance.' },
      { zone: 'Riverside Waterfronts (Lisbon, Porto, Coimbra)', description: 'Riverside plazas over technical basements and car parks (Parque das Nações, Alcântara, Porto Waterfront) with variable water table. EPDM resistant to hydrostatic pressure and humid environment is the reference solution for these locations.' },
    ],
    faqs: [
      { question: 'Does EPDM resist roots from large trees in roof gardens?', answer: 'Yes, 2.0 mm EPDM with EN 13948/FLL certification is the European standard for root resistance. The FLL test exposes the membrane to Agropyron repens and Quercus robur for 24 months — EPDM passes without any puncture, without biocides. For large trees in deep pits, Membriko also specifies perimeter tree pit drainage to avoid root concentration at the membrane.' },
      { question: 'How is the expansion joint between two concrete blocks treated on a platform?', answer: 'Membriko uses pre-fabricated EPDM expansion joint covers with calculated slack for the anticipated movement amplitude — typically ±15-20 mm for Portuguese climatic conditions. The cover is bonded on both flanges to the field membrane with minimum 150 mm overlap each side. No mastic sealants are used — the seal is guaranteed by the vulcanised EPDM itself.' },
      { question: 'What test confirms watertightness before covering the membrane?', answer: 'Membriko performs a flood test of 100% of the installed area before any protection layer or substrate. The test maintains 50 mm of water for a minimum of 24 hours. Any leak is located, repaired and re-tested. Results are photographically documented and included in the handover dossier with the warranty certificate.' },
      { question: 'Does EPDM resist irrigation and fertiliser products used in roof gardens?', answer: 'Yes. EPDM is chemically inert to all agrochemicals used in ornamental irrigation: high-concentration NPK fertilisers, pesticides, fungicides, herbicides and pH correctors. This inertness is intrinsic to the EPDM polymer chemistry — it does not degrade over time.' },
      { question: 'Can I have service vehicles in the same platform as the garden?', answer: 'Yes, with correct zoning. The traffic zone uses EPDM + reinforced load-distributing concrete (≥100 mm, C25/30). The garden zone uses EPDM + drainage + substrate. The transition between zones uses a monolithic EPDM detail. Axle loads up to 3.5 t are compatible — heavier vehicles require structural engineering review.' },
      { question: 'Can EPDM be installed over an existing bitumen waterproofing on a podium being rehabilitated?', answer: 'Yes, subject to substrate condition assessment. If the existing bituminous membrane is bonded and blister-free, EPDM can be bonded over it with compatible primer. Where delamination or chemical degradation is present, full removal is necessary. Membriko performs pull-off testing (EN 12188) and drone infrared thermography to locate wet zones before confirming the rehabilitation method.' },
      { question: 'How is a roof garden drained on a plaza platform?', answer: 'The multi-level system includes: slab slopes (min 1.5%), EPDM membrane, protective geotextile, drainage layer (HDPE plate or Leca 20-40 mm), filter geotextile, mineral substrate. Primary drains penetrate all layers to the membrane. Secondary emergency overflows 50 mm above primary drain inlet level. Each tree pit has a perimeter drainage ring connected to the main drainage layer.' },
      { question: 'What is the environmental impact of EPDM compared with liquid polyurethane membranes?', answer: 'EPDM has lower embodied carbon per year of service life than liquid PU when the PU replacement cycle is included. EPDM contains no chlorine (unlike PVC), requires no biocides for root resistance, and is recyclable at end of life. For projects with BREEAM Mat 05 or LEED v4 MR certification, Membriko provides EPD (Environmental Product Declaration) for installed materials.' },
    ],
    relatedSlugs: ['green-roofs', 'underground-parking', 'expansion-joints'],
  },
}
