import type { ApplicationData } from '../types'

export const undergroundParking: ApplicationData = {
  id: 'underground-parking',
  categoryId: 'civil',
  pt: {
    meta: {
      title: 'Impermeabilização de Estacionamentos Subterrâneos com EPDM | Membriko',
      description: 'Membrana EPDM para lajes e paredes de estacionamentos subterrâneos. Resistente a combustíveis, sais de degelo, cloretos e pressão hidrostática. Portugal.',
      keywords: ['impermeabilização parque estacionamento', 'membrana EPDM garagem subterrânea', 'laje estacionamento impermeável', 'parking subterrâneo impermeabilização'],
    },
    hero: {
      headline: 'Estacionamentos Subterrâneos Impermeáveis com EPDM',
      subtitle: 'Proteja lajes e paredes de estacionamentos subterrâneos com EPDM — resistente a combustíveis, cloretos de sais de degelo, tráfego e pressão hidrostática, com 50+ anos de durabilidade.',
      stats: [
        { value: '50+', label: 'Anos de vida útil' },
        { value: '2,0 mm', label: 'Espessura para uso intenso' },
        { value: 'XD3', label: 'Classe de exposição EN 1992' },
        { value: '20 anos', label: 'Garantia' },
      ],
    },
    problem: {
      title: 'O Desafio dos Estacionamentos Subterrâneos',
      description: 'Os estacionamentos subterrâneos sofrem um conjunto único de agressões: pressão hidrostática do lençol freático, carga dinâmica de tráfego, derrames de combustível e óleo, e cloretos de sais de degelo em veículos que criam corrosão de armaduras. Estacionamentos em Classe de Exposição XD3 segundo EN 1992.',
      points: [
        'Infiltrações na laje de cobertura danificam veículos, corroem armaduras e comprometem a estrutura',
        'Cloretos de sais de degelo nos pneus atingem a armadura e criam corrosão expansiva — custo de reparação 5-12 vezes o da impermeabilização original',
        'Derrames de combustível e óleo degradam membranas betuminosas em 15-20 anos',
        'Fissuração por retração do betão e cargas dinâmicas de tráfego criam caminhos de infiltração progressivos',
      ],
    },
    solution: {
      title: 'A Solução EPDM para Estacionamentos',
      description: 'O EPDM de 2,0 mm instalado pelo método totalmente colado é a membrana de referência para lajes de estacionamento. A colagem total elimina a migração sub-membrana de água em caso de entrada localizada, que num sistema não colado propaga a infiltração para longe do ponto de entrada.',
      points: [
        'Espessura 2,0 mm totalmente colada à laje — sem percurso de migração de água entre membrana e betão',
        'Inertidade química ao cloreto de sódio e cloreto de cálcio — proteção da armadura em Classe XD3',
        'Resistência a combustíveis e óleos em exposição intermitente — recuperação após derrame',
        'Compatível com asfalto coulée (máx. +160°C de contacto), betão polímero e revestimento epóxi',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Resistência a Cloretos (Classe XD3)', description: 'O EPDM é completamente inerte ao NaCl e CaCl₂ de sais de degelo. Impede que iões cloreto atinjam a armadura da laje — a causa primária de deterioração estrutural em estacionamentos com ciclos molhado-seco (EN 1992 Classe XD3).' },
      { icon: 'Layers', title: 'Resistência a Combustíveis e Óleos', description: 'Exposição intermitente a gasolina, gasóleo e óleos lubrificantes causa inchamento reversível máximo de 3-8% no EPDM vulcanizado (ASTM D471) — sem degradação permanente. O betume degradará em meses com a mesma exposição.' },
      { icon: 'Droplets', title: 'Colagem Total — Sem Migração Sub-Membrana', description: 'O método totalmente colado da Membriko elimina o percurso de migração de água entre membrana e betão. Uma fuga localizada num sistema colado não se propaga — pode ser localizada e reparada com levantamento mínimo do pavimento.' },
      { icon: 'Thermometer', title: 'Compatível com Asfalto Coulée', description: 'O EPDM resiste à temperatura de contacto com asfalto coulée até +160°C sem degradação — superior aos limites de qualquer betume modificado. Camada de proteção mecânica intermediária é instalada antes do asfalto quente.' },
      { icon: 'Wrench', title: 'Obra Nova e Reabilitação', description: 'Adequado para estacionamentos novos (instalado antes da proteção e asfalto) e reabilitação de estacionamentos existentes com infiltrações. Diagnóstico por termografia de infravermelhos para localização de zonas húmidas sem levantar o pavimento.' },
      { icon: 'Euro', title: 'Custo de Reparação Estrutural Evitado', description: 'A Membriko estima que o custo de reparação estrutural de estacionamento com penetração de cloretos estabelecida é 5-12 vezes o custo da impermeabilização original. A equação económica a favor do EPDM é irrefutável.' },
    ],
    specs: [
      { label: 'Espessura', value: '2,0 mm (subterrâneo e cobertura) / 1,5 mm (lajes inter-piso protegidas)' },
      { label: 'Resistência a combustíveis (ASTM D471)', value: 'Inchamento < 8% vol.; propriedades ≥ 85% originais' },
      { label: 'Resistência a cloretos', value: 'Inerte — NaCl e CaCl₂ em qualquer concentração' },
      { label: 'Temperatura de contacto com asfalto coulée', value: 'Máximo +160°C sem degradação' },
      { label: 'Elongação na rutura', value: '≥ 300% (típico 380-450%)' },
      { label: 'Estanquidade hidrostática', value: 'Aprovado a 200 kPa (EN 1928 Método A)' },
      { label: 'Proteção obrigatória', value: 'Betão de proteção 50-80 mm ou placa HDPE 8 mm' },
      { label: 'Norma de produto', value: 'EN 13956 Tipo 3 (marcação CE)' },
    ],
    installationSteps: [
      { step: 1, title: 'Levantamento e Projeto de Drenagem', description: 'Visita técnica com medição das pendentes existentes ou cotas de projeto. Definição de pendentes mínimas (1,5% para drenos), espaçamento de drenos (máx. 12-15 m) e dimensionamento da capacidade de escoamento para caudal de limpeza por pressão (5-15 L/min/m²).' },
      { step: 2, title: 'Preparação da Laje e Primer', description: 'Limpeza da laje por jato de ar comprimido. Reparação de ninhos e segregações. Ensaio de resistência de aderência por tracção (EN 12188) — mínimo 0,08 N/mm². Verificação de humidade superficial — máximo 8%. Aplicação de primer por rolo ou pistola airless.' },
      { step: 3, title: 'Instalação da Membrana EPDM (Totalmente Colada)', description: 'Membrana EPDM de 2,0 mm instalada pelo método totalmente colado. Folhas seladas entre si com fita de emenda EPDM de dupla face — sobreposição mínima de 75 mm. Colagem total com adesivo de contacto de qualidade para imersão permanente.' },
      { step: 4, title: 'Pontos Singulares Prefabricados', description: 'Drenos com flanges EPDM integradas coladas à membrana. Juntas de dilatação com perfis EPDM moldados ±25-50 mm. Penetrações de tubagens com mangas EPDM e anel de compressão inox. Arranques em parede com rebatimento mínimo de 200 mm e perfil de acabamento metálico.' },
      { step: 5, title: 'Ensaio de Estanquidade', description: 'Ensaio de estanquidade por inundação (flood test) ou deteção elétrica de fugas (ELD) de 100% da área antes de qualquer proteção. Não negociável — única forma de detetar defeitos pontuais antes de cobrir com materiais definitivos.' },
      { step: 6, title: 'Camada de Proteção Mecânica', description: 'Imediatamente após aprovação do ensaio: instalação de placa de proteção em HDPE (8 mm) ou betão de proteção (50-80 mm). Proteção temporária durante construção antes da proteção definitiva — período mais crítico para danos mecânicos.' },
      { step: 7, title: 'Revestimento de Circulação e Garantia', description: 'Aplicação de asfalto coulée (temperatura controlada max +160°C de contacto), betão polímero ou revestimento epóxi sobre a proteção. Marcação e sinalização. Documentação fotográfica. Emissão de garantia de 20 anos.' },
    ],
    techniques: [
      {
        title: 'Laje de Tráfego com EPDM Totalmente Colado',
        description: 'EPDM 2,0 mm instalado sobre a laje estrutural pelo método totalmente colado, coberto por proteção mecânica (HDPE ou betão simples) e revestimento de desgaste (asfalto coulée, betão polímero ou revestimento epóxi). Sistema standard para estacionamentos de tráfego intenso.',
        pros: ['Colagem total elimina migração sub-membrana e facilita localização de fugas', 'Compatível com asfalto coulée, betão polímero e sistemas de resina epóxi', 'Adequado para tráfego de veículos ligeiros a pesados com betão de proteção dimensionado', 'Renovação do revestimento de desgaste sem substituição da membrana — independentes'],
        cons: ['Reparação requer levantamento do revestimento de desgaste na zona afetada', 'Instalação exige preparação de superfície rigorosa — humidade máxima 8%'],
      },
      {
        title: 'Pré-Aplicação para Paredes Enterradas',
        description: 'Para paredes em contacto com o solo (método pré-aplicado), EPDM fixado mecanicamente à contenção antes do vazamento do betão. O betão estrutural liga diretamente à face interna da membrana, criando ligação mecânica sem percurso de água longitudinal.',
        pros: ['Aplicável quando a face exterior não é acessível após construção', 'Betão liga diretamente à membrana — sem percurso de migração', 'Ideal para paredes de estacas moldadas, berlim ou paredes de vala'],
        cons: ['Requer coordenação rigorosa com o faseamento da betonagem', 'Não aplicável em reabilitação de paredes existentes'],
      },
      {
        title: 'Reabilitação com EPDM sobre Betume Degradado',
        description: 'Para estacionamentos existentes com impermeabilização betuminosa degradada (instalada nos anos 1990-2000 com vida útil esgotada), EPDM sobre betume existente aderido ou sobre laje após remoção total. Diagnóstico por termografia de infravermelhos antes de confirmar o método.',
        pros: ['Evita remoção total quando o betume existente está aderido', 'Vida útil renovada de 50+ anos após reabilitação', 'Diagnóstico por termografia sem levantar o pavimento existente'],
        cons: ['Ensaio de arranque (EN 12188) obrigatório para confirmar aderência do suporte', 'Se o betume apresenta bolhas ou delaminação, remoção total é necessária'],
      },
    ],
    comparison: [
      { feature: 'Resistência a cloretos (sais de degelo)', epdm: 'Inerte — NaCl e CaCl₂ qualquer conc.', alternatives: [{ name: 'Betume modificado APP', value: 'Ataque progressivo por cloretos concentrados' }, { name: 'PVC plastificado', value: 'Plastificantes extraídos por hidrocarbonetos' }] },
      { feature: 'Resistência a combustíveis e óleos', epdm: 'Inchamento reversível < 8% (ASTM D471)', alternatives: [{ name: 'Betume modificado APP', value: 'Dissolução progressiva — falha em meses' }, { name: 'PU líquido', value: 'Boa em exposição intermitente' }] },
      { feature: 'Vida útil prevista', epdm: '50+ anos', alternatives: [{ name: 'Betume modificado APP', value: '15-20 anos em ambiente XD3' }, { name: 'PU líquido', value: '8-15 anos (re-aplicação necessária)' }] },
      { feature: 'Compatibilidade com asfalto coulée', epdm: 'Sim — até +160°C de contacto', alternatives: [{ name: 'PU líquido', value: 'Não — sensível a temperatura alta' }, { name: 'Betume modificado APP', value: 'Sim — mas vida útil inferior' }] },
      { feature: 'Deteção de fuga em laje coberta', epdm: 'Termografia IR + ELD (sem levantar pavimento)', alternatives: [{ name: 'Betume modificado APP', value: 'Difícil — requer abertura do pavimento' }, { name: 'PU líquido', value: 'Difícil — espessura variável' }] },
      { feature: 'Custo estrutural evitado (cloretos)', epdm: 'Proteção total da armadura', alternatives: [{ name: 'Betume modificado APP', value: 'Reparação estrutural: 5-12× custo da membrana' }, { name: 'PU líquido', value: 'Reparação estrutural: 5-10× custo da membrana' }] },
    ],
    climate: [
      { zone: 'Norte Atlântico (Lençol Freático Elevado)', description: 'Alta precipitação no norte (Minho, Douro Litoral) cria lençol freático elevado em estacionamentos subterrâneos. O EPDM aprovado a 200 kPa (EN 1928 Método A — 20 m de coluna de água) cobre com margem as pressões de projeto típicas de 10-40 kPa.' },
      { zone: 'Lisboa e Porto (Aluviões e Cloretos Marinhos)', description: 'Estacionamentos subterrâneos em Lisboa (Baixa, Chiado, Parque das Nações) e Porto sobre aluviões com lençol freático elevado. Adicionalmente, ambiente marinho com aerossóis salgados nos veículos amplificam o risco de cloretos na armadura.' },
      { zone: 'Zonas de Neve (Serra da Estrela, Peneda-Gerês)', description: 'Sais de degelo NaCl e CaCl₂ aplicados nas estradas são arrastados pelos veículos para os estacionamentos. Concentram-se nos drenos e nas juntas. O EPDM é completamente inerte a estas soluções de cloreto em qualquer concentração.' },
      { zone: 'Estacionamentos de Centros Comerciais (Tráfego Intenso)', description: 'Estacionamentos de grande rotatividade em centros comerciais têm exposição elevada a combustíveis, óleos e produtos de limpeza. O EPDM resiste a estas agressões em exposição intermitente sem degradação permanente — ao contrário do betume que falha em 15-20 anos.' },
      { zone: 'Zonas Urbanas com Poluição (Grandes Cidades)', description: 'Estacionamentos urbanos acumulam óleos, combustíveis, resíduos de pneus e produtos de limpeza clorados. A inertidade química completa do EPDM a este cocktail de agentes é a razão da sua especificação em estacionamentos de referência em Portugal.' },
    ],
    faqs: [
      { question: 'O EPDM aguenta veículos pesados como autocarros e camiões de serviço?', answer: 'Sim, desde que protegido adequadamente com betão de proteção dimensionado para as cargas previstas. O EPDM é a barreira impermeável — a carga é suportada e distribuída pela camada de betão de proteção. Para estacionamentos de veículos pesados, a Membriko dimensiona a espessura e armadura do betão de proteção para os eixos previstos conforme EN 1991-1-1.' },
      { question: 'O EPDM resiste ao óleo e ao combustível dos veículos?', answer: 'Sim. O EPDM vulcanizado resiste bem à exposição intermitente a óleos e combustíveis — o padrão de exposição típico num estacionamento. O inchamento volumétrico em imersão total prolongada é de 3-8%, mas em exposição pontual de derrames o inchamento é negligenciável e reversível. As propriedades mecânicas são retidas acima de 85% mesmo após exposição prolongada (ASTM D471).' },
      { question: 'Posso usar EPDM para reabilitar um estacionamento com infiltrações?', answer: 'Sim. Em reabilitação, a Membriko realiza primeiro diagnóstico por termografia de infravermelhos (drone) para localizar zonas húmidas sem levantar o pavimento. Se o betume existente está aderido, o EPDM pode ser colado sobre ele com primer compatível. Se há delaminação ou betume degradado, é necessária remoção total antes da instalação do EPDM.' },
      { question: 'O que é a Classe de Exposição XD3 e como afeta a impermeabilização?', answer: 'A Classe de Exposição XD3 (EN 1992) aplica-se a estruturas de betão sujeitas a cloretos em ciclos molhado-seco — como lajes de estacionamento onde os sais de degelo dos veículos alternam com secagem. Nesta classe, a proteção da armadura é crítica: a penetração de iões cloreto desencadeia corrosão que expande 2,5 a 6 vezes o volume original do aço, fragmentando o betão. O EPDM impede fisicamente que os cloretos atinjam a armadura.' },
      { question: 'Como se deteta uma fuga na membrana EPDM num estacionamento com pavimento betuminoso?', answer: 'A Membriko utiliza: (1) inspeção visual do teto do piso inferior — manchas de eflorescência indicam localização aproximada; (2) termografia infravermelha — a membrana húmida sob o pavimento retém calor de forma diferente da seca; (3) deteção elétrica de fugas (ELD) — identifica exatamente o ponto de entrada sem levantar o pavimento. Após localização, levantamento mínimo do pavimento confirma e permite a reparação.' },
      { question: 'Quanto tempo demora a instalação EPDM num estacionamento sem interromper a atividade?', answer: 'Em reabilitações, a Membriko planeia a instalação por zonas de 200-500 m² mantendo o resto operacional. O rendimento de instalação é de 300-500 m² por dia, permitindo a conclusão de um estacionamento de 1.000 m² em 3-5 dias de trabalho efetivo. Para novas construções, a mobilização é dimensionada para o prazo crítico do projeto.' },
      { question: 'O EPDM cumpre as normas de segurança contra incêndio para estacionamentos (DL 220/2008)?', answer: 'O EPDM é classificado como Classe E segundo a EN 13501-1. Em estacionamentos, a membrana é instalada sob a camada de proteção e o pavimento de desgaste — não é uma superfície exposta sujeita às classificações de reação ao fogo mais exigentes. A Membriko fornece documentação de classificação ao fogo em todas as propostas e coordena com o responsável pelo projeto de SCIE.' },
      { question: 'Qual a diferença entre impermeabilização de estacionamento com EPDM vs sistema de PU líquido?', answer: 'A diferença principal está na consistência e durabilidade. O PU líquido é aplicado por rolo com espessura variável (1-2 mm) e requer re-aplicação a cada 8-15 anos. O EPDM tem espessura constante de fábrica (2,0 mm) e vida útil de 50+ anos. Em estacionamentos de longa vida útil, o custo total de propriedade do EPDM é significativamente inferior ao do PU.' },
      { question: 'Como se trata o ponto crítico da junção laje de fundo com as paredes periféricas?', answer: 'A junção laje/parede é o ponto de maior risco em qualquer impermeabilização de estacionamento subterrâneo. A Membriko resolve com continuidade total: a membrana EPDM da laje dobra na vertical sobre a parede com largura mínima de 300 mm, sem emenda no ângulo. Peças de enchimento EPDM pré-formadas (fillets) são coladas no ângulo interior para eliminar tensões de tração no canto.' },
    ],
    relatedSlugs: ['foundations', 'basements', 'tunnels'],
  },
  en: {
    meta: {
      title: 'Underground Car Park Waterproofing with EPDM | Membriko',
      description: 'EPDM membrane for underground car park slabs and walls. Resistant to fuels, de-icing salt chlorides and hydrostatic pressure. Portugal.',
      keywords: ['car park waterproofing EPDM', 'underground garage membrane', 'parking slab waterproofing', 'underground car park waterproofing Portugal'],
    },
    hero: {
      headline: 'Waterproof Underground Car Parks with EPDM',
      subtitle: 'Protect underground car park slabs and walls with EPDM — resistant to fuels, de-icing salt chlorides, traffic and hydrostatic pressure, with 50+ years durability.',
      stats: [
        { value: '50+', label: 'Years service life' },
        { value: '2.0 mm', label: 'Thickness for intensive use' },
        { value: 'XD3', label: 'EN 1992 exposure class' },
        { value: '20 years', label: 'Guarantee' },
      ],
    },
    problem: {
      title: 'The Underground Car Park Challenge',
      description: 'Underground car parks suffer a unique combination of aggressions: water table hydrostatic pressure, dynamic traffic loads, fuel and oil spills, and de-icing salt chlorides from vehicles that trigger reinforcement corrosion. Car parks fall under Exposure Class XD3 per EN 1992.',
      points: [
        'Roof slab infiltrations damage vehicles, corrode reinforcement and compromise the structure',
        'De-icing salt chlorides from vehicle tyres reach reinforcement causing expansive corrosion — structural repair costs 5-12 times the original waterproofing',
        'Fuel and oil spills degrade bituminous membranes within 15-20 years',
        'Concrete shrinkage cracking and dynamic traffic loads create progressive infiltration pathways',
      ],
    },
    solution: {
      title: 'The EPDM Solution for Car Parks',
      description: '2.0 mm EPDM installed by the fully bonded method is the reference membrane for car park slabs. Full bonding eliminates sub-membrane water migration in case of localised entry — in a non-bonded system, infiltration propagates far from the entry point.',
      points: [
        '2.0 mm fully bonded EPDM — no sub-membrane water migration pathway between membrane and concrete',
        'Chemical inertness to sodium chloride and calcium chloride — reinforcement protection in Class XD3',
        'Fuel and oil resistance under intermittent exposure — recovery after spill',
        'Compatible with mastic asphalt (max +160°C contact), polymer concrete and epoxy coating',
      ],
    },
    benefits: [
      { icon: 'Shield', title: 'Chloride Resistance (Class XD3)', description: 'EPDM is completely inert to NaCl and CaCl₂ from de-icing salts. Prevents chloride ions from reaching the slab reinforcement — the primary cause of structural deterioration in car parks with wet-dry cycling (EN 1992 Class XD3).' },
      { icon: 'Layers', title: 'Fuel and Oil Resistance', description: 'Intermittent exposure to petrol, diesel and lubricating oils causes maximum reversible swelling of 3-8% in vulcanised EPDM (ASTM D471) — no permanent degradation. Bitumen degrades irreversibly with the same exposure within months.' },
      { icon: 'Droplets', title: 'Full Bond — No Sub-Membrane Migration', description: 'Membriko\'s fully bonded method eliminates the sub-membrane water migration pathway between membrane and concrete. A localised leak in a bonded system does not propagate — it can be located and repaired with minimal paving removal.' },
      { icon: 'Thermometer', title: 'Compatible with Mastic Asphalt', description: 'EPDM withstands mastic asphalt contact temperatures up to +160°C without degradation — exceeding the limits of any modified bitumen. A mechanical protection layer is installed between the EPDM and hot mastic asphalt.' },
      { icon: 'Wrench', title: 'New Build and Rehabilitation', description: 'Suitable for new car parks (installed before protection and asphalt) and rehabilitation of existing car parks with infiltrations. Infrared thermography diagnosis for locating wet zones without lifting the existing pavement.' },
      { icon: 'Euro', title: 'Structural Repair Costs Avoided', description: 'Membriko estimates that the cost of structural repair for a car park with established chloride penetration is 5-12 times the cost of the original waterproofing. The economic case for EPDM is irrefutable.' },
    ],
    specs: [
      { label: 'Thickness', value: '2.0 mm (underground and roof) / 1.5 mm (protected inter-floor slabs)' },
      { label: 'Fuel resistance (ASTM D471)', value: 'Swelling < 8% vol.; properties ≥ 85% original' },
      { label: 'Chloride resistance', value: 'Inert — NaCl and CaCl₂ at any concentration' },
      { label: 'Mastic asphalt contact temperature', value: 'Maximum +160°C without degradation' },
      { label: 'Elongation at break', value: '≥ 300% (typical 380-450%)' },
      { label: 'Hydrostatic watertightness', value: 'Approved at 200 kPa (EN 1928 Method A)' },
      { label: 'Mandatory protection', value: 'Protection concrete 50-80 mm or HDPE plate 8 mm' },
      { label: 'Product standard', value: 'EN 13956 Type 3 (CE marking)' },
    ],
    installationSteps: [
      { step: 1, title: 'Survey and Drainage Design', description: 'Technical visit with existing slope measurement or design level survey. Definition of minimum slopes (1.5% to drains), drain spacing (max 12-15 m) and drainage capacity for pressure-washing flow (5-15 L/min/m²).' },
      { step: 2, title: 'Slab Preparation and Primer', description: 'Slab cleaning by compressed air blasting. Void and segregation repair. Pull-off adhesion testing (EN 12188) — minimum 0.08 N/mm². Surface moisture check — maximum 8%. Primer application by roller or airless spray.' },
      { step: 3, title: 'EPDM Membrane Installation (Fully Bonded)', description: '2.0 mm EPDM membrane installed by fully bonded method. Sheets sealed with dual-face EPDM joint tape — minimum 75 mm overlap. Full bonding with contact adhesive rated for permanent immersion.' },
      { step: 4, title: 'Pre-Fabricated Singular Points', description: 'Drains with integrated EPDM flanges bonded to membrane. Expansion joints with moulded EPDM profiles ±25-50 mm. Pipe penetrations with EPDM sleeves and stainless steel compression ring. Wall upstands with minimum 200 mm turn-up and metal termination bar.' },
      { step: 5, title: 'Watertightness Testing', description: 'Flood test or electric leak detection (ELD) of 100% of area before any protection layer. Non-negotiable — the only way to detect point defects before covering with permanent materials.' },
      { step: 6, title: 'Mechanical Protection Layer', description: 'Immediately after test approval: HDPE protection plate (8 mm) or protection concrete (50-80 mm) installation. Temporary construction protection before definitive — the most critical period for mechanical damage.' },
      { step: 7, title: 'Circulation Surface and Warranty', description: 'Application of mastic asphalt (controlled temperature max +160°C contact), polymer concrete or epoxy coating over protection. Markings and signage. Photographic documentation. Issue of 20-year warranty.' },
    ],
    techniques: [
      {
        title: 'Traffic Slab with Fully Bonded EPDM',
        description: '2.0 mm EPDM installed over structural slab by fully bonded method, covered by mechanical protection (HDPE or plain concrete) and wearing surface (mastic asphalt, polymer concrete or epoxy coating). Standard system for high-traffic car parks.',
        pros: ['Full bonding eliminates sub-membrane migration and facilitates leak location', 'Compatible with mastic asphalt, polymer concrete and epoxy resin systems', 'Suitable for light to heavy vehicle traffic with designed protection concrete', 'Wearing surface renewal without membrane replacement — independent systems'],
        cons: ['Repair requires wearing surface lifting in the affected zone', 'Installation requires rigorous surface preparation — maximum 8% moisture'],
      },
      {
        title: 'Pre-Applied System for Buried Walls',
        description: 'For walls in contact with soil (pre-applied method), EPDM fixed mechanically to excavation support before concrete pouring. Structural concrete bonds directly to the membrane inner face, creating mechanical bond without longitudinal water migration pathway.',
        pros: ['Applicable when exterior face is not accessible after construction', 'Concrete bonds directly to membrane — no migration pathway', 'Ideal for bored pile walls, sheet piles or trench walls'],
        cons: ['Requires rigorous coordination with concreting phasing', 'Not applicable to rehabilitation of existing walls'],
      },
      {
        title: 'Rehabilitation over Degraded Bitumen',
        description: 'For existing car parks with degraded bituminous waterproofing (installed in the 1990s-2000s with exhausted service life), EPDM over bonded existing bitumen or over slab after full removal. Infrared thermography diagnosis before confirming the method.',
        pros: ['Avoids full removal when existing bitumen is bonded', 'Service life renewed for 50+ years after rehabilitation', 'Thermography diagnosis without lifting existing pavement'],
        cons: ['Pull-off test (EN 12188) mandatory to confirm substrate adhesion', 'If bitumen shows blistering or delamination, full removal is required'],
      },
    ],
    comparison: [
      { feature: 'Chloride resistance (de-icing salts)', epdm: 'Inert — NaCl and CaCl₂ any concentration', alternatives: [{ name: 'APP modified bitumen', value: 'Progressive chloride attack at concentrations' }, { name: 'Plasticised PVC', value: 'Plasticisers extracted by hydrocarbons' }] },
      { feature: 'Fuel and oil resistance', epdm: 'Reversible swelling < 8% (ASTM D471)', alternatives: [{ name: 'APP modified bitumen', value: 'Progressive dissolution — fails within months' }, { name: 'Liquid PU', value: 'Good under intermittent exposure' }] },
      { feature: 'Expected service life', epdm: '50+ years', alternatives: [{ name: 'APP modified bitumen', value: '15-20 years in XD3 environment' }, { name: 'Liquid PU', value: '8-15 years (re-application required)' }] },
      { feature: 'Mastic asphalt compatibility', epdm: 'Yes — up to +160°C contact', alternatives: [{ name: 'Liquid PU', value: 'No — sensitive to high temperature' }, { name: 'APP modified bitumen', value: 'Yes — but shorter service life' }] },
      { feature: 'Leak detection under paved slab', epdm: 'IR thermography + ELD (no pavement lifting)', alternatives: [{ name: 'APP modified bitumen', value: 'Difficult — requires pavement opening' }, { name: 'Liquid PU', value: 'Difficult — variable thickness' }] },
      { feature: 'Structural repair cost avoided (chlorides)', epdm: 'Full reinforcement protection', alternatives: [{ name: 'APP modified bitumen', value: 'Structural repair: 5-12× membrane cost' }, { name: 'Liquid PU', value: 'Structural repair: 5-10× membrane cost' }] },
    ],
    climate: [
      { zone: 'Atlantic North (High Water Table)', description: 'High rainfall in northern Portugal (Minho, Douro Litoral) creates elevated water table in underground car parks. EPDM approved at 200 kPa (EN 1928 Method A — 20 m water column) provides significant margin over typical design pressures of 10-40 kPa.' },
      { zone: 'Lisbon and Porto (Alluvial Ground and Marine Chlorides)', description: 'Underground car parks in Lisbon (Baixa, Chiado, Parque das Nações) and Porto over alluvial ground with high water table. Additionally, marine environment with salt aerosols in vehicles amplifies chloride risk to reinforcement.' },
      { zone: 'Snow Zones (Serra da Estrela, Peneda-Gerês)', description: 'NaCl and CaCl₂ de-icing salts applied on roads are carried by vehicles into car parks. They concentrate at drains and joints. EPDM is completely inert to these chloride solutions at any concentration.' },
      { zone: 'Shopping Centre Car Parks (High Traffic)', description: 'High-turnover car parks at shopping centres have high exposure to fuels, oils and cleaning products. EPDM resists these aggressions under intermittent exposure without permanent degradation — unlike bitumen which fails in 15-20 years.' },
      { zone: 'Urban Zones with Pollution (Major Cities)', description: 'Urban car parks accumulate oils, fuels, tyre residues and chlorinated cleaning products. EPDM\'s complete chemical inertness to this cocktail of agents is the reason for its specification in reference car parks throughout Portugal.' },
    ],
    faqs: [
      { question: 'Does EPDM withstand heavy vehicles such as service buses and lorries?', answer: 'Yes, provided it is adequately protected with protection concrete designed for the expected loads. EPDM is the impermeable barrier — load is supported and distributed by the protection concrete layer. For heavy vehicle car parks, Membriko designs the protection concrete thickness and reinforcement for the specified axle loads per EN 1991-1-1.' },
      { question: 'Does EPDM resist vehicle oil and fuel?', answer: 'Yes. Vulcanised EPDM withstands intermittent exposure to oils and fuels well — the typical exposure pattern in a car park. Volumetric swelling under prolonged total immersion is 3-8%, but in point spill exposure, swelling is negligible and reversible. Mechanical properties are retained above 85% even after prolonged exposure (ASTM D471).' },
      { question: 'Can EPDM be used to rehabilitate a car park with infiltrations?', answer: 'Yes. In rehabilitation, Membriko first performs infrared thermography diagnosis (drone) to locate wet zones without lifting the pavement. If existing bitumen is bonded, EPDM can be bonded over it with compatible primer. If delamination or degraded bitumen is present, full removal before EPDM installation is required.' },
      { question: 'What is Exposure Class XD3 and how does it affect waterproofing?', answer: 'Exposure Class XD3 (EN 1992) applies to concrete structures subject to chlorides in wet-dry cycles — such as car park slabs where de-icing salts from vehicles alternate with drying. In this class, reinforcement protection is critical: chloride ion penetration triggers corrosion expanding 2.5 to 6 times the original steel volume, fragmenting the concrete cover. EPDM physically prevents chlorides from reaching the reinforcement.' },
      { question: 'How is an EPDM membrane leak detected in a car park with asphalt pavement?', answer: 'Membriko uses: (1) visual inspection of the lower floor ceiling — efflorescence stains indicate approximate location; (2) infrared thermography — wet membrane under pavement retains heat differently than dry; (3) electric leak detection (ELD) — identifies the exact entry point without lifting the pavement. After location, minimal pavement lifting confirms and allows the repair.' },
      { question: 'How long does EPDM installation take in a car park without interrupting operations?', answer: 'In rehabilitation, Membriko plans installation in zones of 200-500 m² keeping the rest operational. Installation output is 300-500 m² per day, allowing completion of a 1,000 m² car park in 3-5 effective working days. For new construction, mobilisation is sized for the project critical path.' },
      { question: 'Does EPDM comply with fire safety standards for car parks (DL 220/2008)?', answer: 'EPDM is classified as Class E per EN 13501-1. In car parks, the membrane is installed under the protection layer and wearing surface — it is not an exposed surface subject to the most demanding fire reaction classifications. Membriko provides fire classification documentation in all proposals and coordinates with the SCIE project manager.' },
      { question: 'What is the critical detail for the slab-to-perimeter wall junction?', answer: 'The slab-to-wall junction is the highest-risk point in any underground car park waterproofing. Membriko resolves this with full continuity: the EPDM membrane from the slab is turned up vertically on the wall with minimum 300 mm width, without a seam at the angle. Pre-formed EPDM fillet pieces are bonded at the interior corner to eliminate tensile stress concentration at the turn.' },
    ],
    relatedSlugs: ['foundations', 'basements', 'tunnels'],
  },
}
